### ISSUE TITLE
[BUG] - 0.8.0-dev error 

### ISSUE THREAD

**Issue by vingerha** [m4dm4rtig4n/myelectricaldata#139]
```
2022-11-23 08:23:42.584 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-11-23 08:23:42.585 -     INFO :  [xxx] RÉCUPÉRATION DE LA CONSOMMATION JOURNALIÈRE :
2022-11-23 08:23:42.585 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-11-23 08:23:42.598 -     INFO :  Récupération des données : 2022-10-18 => 2022-11-23
2022-11-23 08:23:42.879 -     INFO :   => Chargement des données depuis MyElectricalData 2022-10-18 => 2022-11-23
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 0c07baa8d7b2, base
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table config already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line 561, in run_cmd
    fn(
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "alembic/env.py", line 82, in <module>
    run_migrations_online()
  File "alembic/env.py", line 76, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/environment.py", line 853, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 623, in run_migrations
    step.migration_fn(**kw)
  File "/app/alembic/versions/0c07baa8d7b2_base.py", line 21, in upgrade
    op.create_table('config',
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/ops.py", line 1254, in create_table
    return operations.invoke(op)
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/base.py", line 399, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 114, in create_table
    operations.impl.create_table(table)
  File "/usr/local/lib/python3.9/site-packages/alembic/ddl/impl.py", line 354, in create_table
    self._exec(schema.CreateTable(table))
  File "/usr/local/lib/python3.9/site-packages/alembic/ddl/impl.py", line 195, in _exec
    return conn.execute(construct, multiparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1472, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table config already exists
[SQL: 
CREATE TABLE config (
	"key" TEXT NOT NULL, 
	value TEXT NOT NULL, 
	PRIMARY KEY ("key")
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-11-23 08:23:45.020 -     INFO :  Configure Databases
2022-11-23 08

**Comment by vingerha** [comment]
Sachant que les données sont la. 
Je ne suis pas sûre non plus sur le quota, depuis hier (upgrade de 077) je n'avais pas eu des maj jusqua 0600.
Ce matin j'ai changé de token + restart... les données détailées de hier sont maintenant là... mais l'histoire ne change pas, que des donées depuis 2021-06-30
Pour les données journaliers: je reçoit des messages comme si-dessous. Mon linky est installé vers ce date donc je le comprends mais.... je ne sais pas si la recherche pour des données non-existante pèse sur le quota?
```
2022-11-23 08:24:01.604 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-11-23 08:24:01.604 -    ERROR : 
2022-11-23 08:24:01.604 -    ERROR :  Echec de la récupération des données.
2022-11-23 08:24:01.605 -    ERROR :   => no measure found for this usage point
2022-11-23 08:24:01.605 -    ERROR :   => 2020-03-26 -> 2020-05-01
2022-11-23 08:24:01.605 -    ERROR : 
2022-11-23 08:24:01.605 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by pbranly** [comment]
Hello
Tu as vu que ça écrit dans une autre base influx ? Chez moi c’est ok. Mais j’ai du changer pas mal de chose dans les noms de bases 
Phil

**Comment by vingerha** [comment]
Ensuite.... ces chiffres ne sont pas corrects
```
monthly_evolution: -104.19
current_month_evolution: -74.95
```
c'est [plutot ça (de ma version 077)...mais je pense que 077 n'était pas parfait non-plus/..il faut je refait une calcul
```
monthly_evolution: -51.02
current_month_evolution: -45.83
```
et pour finaliser...je manque encore mes autres sensors (voir HCF message avant)


Comme écrit.... je suis dispo pour tester :)

**Comment by vingerha** [comment]
@pbranly je n'utilise pas influx, dans le config enable: false 
```
cycle: 14400  # 2H
debug: true
wipe_influxdb: false
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: false
#  hostname: influxdb
#  port: 8086
#  token: myelectricaldata
#  org: myelectricaldata
#  bucket: myelectricaldata
.....
```

**Comment by pbranly** [comment]
Mais tu as erase ta base cache ? Car sinon ça marche pas .

**Comment by vingerha** [comment]
J'ai migré selon les instructions sur HACF
![image](https://user-images.githubusercontent.com/44190435/203498545-5b1d3c4a-948f-41bd-bb75-454a9c77b451.png)

**Comment by m4dm4rtig4n** [comment]
@vingerha sur la dernière version j'ai rework 2 truc qui vont peut être corrigé tes soucis de valeur remonter sur HA.

**Comment by vingerha** [comment]
Avec :latest, même erreur sur les sensors 
Un + : l'erreur autour du config table n'est plus là

**Comment by vingerha** [comment]
Moins bon car bloqué sur (voir si-dessous)... 
Et, avec :latest, je n'ai pas de soucis avec config-table...mais aussi pas d'autres sensors non plus

```
2022-11-23 14:20:07.073 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-11-23 14:20:07.073 -     INFO :  Check config.yaml :
2022-11-23 14:20:07.073 -     INFO :   => Config valid
2022-11-23 14:20:07.098 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-11-23 14:20:07.098 -     INFO :  LOADING CONFIGURATION...
2022-11-23 14:20:07.098 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-11-23 14:20:07.099 -     INFO :  25960347298299
2022-11-23 14:20:07.119 -     INFO :    => Success
2022-11-23 14:20:07.120 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-11-23 14:20:07.120 -     INFO :  Connect to MQTT broker 192.168.1.20:1883
2022-11-23 14:20:07.124 -     INFO :   => Connection success
```

**Comment by vingerha** [comment]
j'ai testé les deux....

**Comment by pbranly** [comment]
Tu dois avoir un soucis dans ton fichier de config.

**Comment by vingerha** [comment]
Pourquoi? J'a'mon sensor de base.... que les autres sont manquants

**Comment by pbranly** [comment]
Aaaaa il y en a plus d’autres ! Mad les a retires . Il ne subsiste qu’un seul sensor

**Comment by pbranly** [comment]
C’est tout ce que j’ai avec mes 2 pdl tous les autres dispos avec enedisgateway2mqtt ne sont plus supportés par myelectricaldata
![9FFBBB23-B257-4BC6-81F5-282880A656B1](https://user-images.githubusercontent.com/22018509/203559624-c4071f8e-dbb4-4d24-bd3f-cb115aea935e.jpeg)

**Comment by vingerha** [comment]
OK, mais pourquoi l'erreur pour les autres sensors?

**Comment by pbranly** [comment]
Quels autres sensors ?

**Comment by vingerha** [comment]
Hmmm... j'avais peut-être / probablement mal lu / interprêté
```
2022-11-22 11:19:19.836 -    ERROR :  Erreur lors de l'exportation des données dans MQTT
2022-11-22 11:19:19.836 -    ERROR : 
2022-11-22 11:19:19.836 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-11-22 11:19:19.838 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-11-22 11:19:19.838 -     INFO :  [xxxx] EXPORTATION DES DONNÉES DANS HOME ASSISTANT (VIA MQTT)
2022-11-22 11:19:19.838 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-11-22 11:19:19.992 -     INFO :   - peak_offpeak_percent_hp / peak_offpeak_percent_hc
2022-11-22 11:19:19.995 -     INFO :   - current_week
2022-11-22 11:19:20.007 -     INFO :   - last_week
2022-11-22 11:19:20.019 -     INFO :   - current_week_evolution
2022-11-22 11:19:20.019 -     INFO :   - yesterday_evolution
2022-11-22 11:19:20.042 -     INFO :   - current_week_last_year
2022-11-22 11:19:20.058 -     INFO :   - last_month
2022-11-22 11:19:20.071 -     INFO :   - current_
```

**Comment by vingerha** [comment]
J'attendais plusiqeurs comme avec enedisgateway et l'erreur est curieux car je voix tous les données

**Comment by m4dm4rtig4n** [comment]
@vingerha sur la 0.8.1-dev j'ai refait une passe sur les stats d'évolution de consomation que j'envoie à HA.

**Comment by vingerha** [comment]
MAJ... 
Dans config.py j'ai reduit le max_days et maintenant mieux
Question: pour quoi dans config.py et pas dans config.yaml?

Les deux choses qui restent:
1. erreur sur 'détails' ... les données sont dans le bdd, pourquoi chercher chez enedis
```
2022-11-24 16:01:32.938 -     INFO :   => Chargement des données depuis MyElectricalData 2022-11-17 => 2022-11-24
2022-11-24 16:01:33.118 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-11-24 16:01:33.118 -    ERROR : 
2022-11-24 16:01:33.119 -    ERROR :  Echec de la récupération des données.
2022-11-24 16:01:33.119 -    ERROR :   => Vous avez dépassé votre quota journalier (50)
2022-11-24 16:01:33.120 -    ERROR :   => 2022-11-10 -> 2022-11-17
```
2. erreur python
```
2022-11-24 16:01:42.247 -     INFO :   2022-01-01 => 2022-11-23
Traceback (most recent call last):
  File "/app/models/jobs.py", line 118, in job_import_data
    ExportMqtt(self.usage_point_id, "consumption").detail_annual(
  File "/app/models/export_mqtt.py", line 308, in detail_annual
    self.load_detail_data(date_begin_current, date_end, price_hp, price_hc, sub_prefix)
  File "/app/models/export_mqtt.py", line 239, in load_detail_data
    output[measure_type]["this_year_watt"] = output[measure_type]["this_year_watt"] + watt
KeyError: 'base'
2022-11-24 16:01:43.347 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
```

**Comment by m4dm4rtig4n** [comment]
Les valeurs dans le config.py sont la renseigner les limites d'Enedis qui ne transmet les données de plus de 2 ans en detail et 3 ans en daily.
Les augmenter va augmenter le nombre d'erreur et surcharger pour rien la passerelle.

**Comment by vingerha** [comment]
Compris...mais chez moi l'intégration continuait a chercher des données non-existants semblement affectuer le quota et pour cela je les ai reduit vers 850 et 550.
Autre question...mon cycle vers 04:01 ne cherche pas des données de hier, est-ce que t'as mis un créneau expres car 'normalement' ils ne sont pas encore dispo? Le cycle (manuel restart) de 07:50 l'a fait....alors ma question

**Comment by m4dm4rtig4n** [comment]
J'ai remarque un soucis sur le cron automatiquement de la veille. faut que je jete un oeil.

**Comment by vingerha** [comment]
Closed as this thread became too long and no longer 080 specific, opened other ticket
