### ISSUE TITLE
Version 0.8.2-dev: internal Web access broken for PDL 2

### ISSUE THREAD

**Issue by pbranly** [m4dm4rtig4n/myelectricaldata#149]
Hi
First pdl is working well but access to pdl 2 is broken:
![2022-11-26_09-09](https://user-images.githubusercontent.com/22018509/204079204-66757d4e-0d35-4e82-abd1-83b614888684.png)

traces gives:

2022-11-26 09:08:52.563 -    ERROR : Exception on /usage_point_id/xxxxxxxxxx2 [GET]

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app

    response = self.full_dispatch_request()

  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request

    rv = self.dispatch_request()

  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)

  File "/app/main.py", line 139, in usage_point_id

    return UsagePointId(usage_point_id).display()

  File "/app/templates/usage_point_id.py", line 176, in display

    recap_consumption = self.recap(data=self.recap_consumption_data)

  File "/app/templates/usage_point_id.py", line 536, in recap

    data_last_years = round((100 * int(data)) / int(data_last_years) - 100, 2)

ZeroDivisionError: division by zero

**Comment by m4dm4rtig4n** [comment]
Déjà fix dans la 0.8.3-dev qui va pas tarder à sortir
