### ISSUE TITLE
[BUG] & [SOLUTION] - define 'base'

### ISSUE THREAD

**Issue by vingerha** [m4dm4rtig4n/myelectricaldata#150]
Error in MQTT export
```
Traceback (most recent call last):
  File "/app/models/jobs.py", line 127, in job_import_data
    ExportMqtt(self.usage_point_id, "consumption").detail_annual(
  File "/app/models/export_mqtt.py", line 308, in detail_annual
    self.load_detail_data(date_begin_current, date_end, price_hp, price_hc, sub_prefix)
  File "/app/models/export_mqtt.py", line 239, in load_detail_data
    output[measure_type]["this_year_watt"] = output[measure_type]["this_year_watt"] + watt
KeyError: 'base'
```

Solution: export_mqtt.py: add 'base' to output definition
![image](https://user-images.githubusercontent.com/44190435/204126150-8e4bcc96-bce5-4d3d-b77b-064d41adeb73.png)

**Comment by vingerha** [comment]
Closed and created a pull request for it
