### ISSUE TITLE
[BUG] - Utilisation anormale des ressources système => system crash

### ISSUE THREAD

**Issue by buddy31130** [m4dm4rtig4n/myelectricaldata#158]
**Description du bug**
Bonjour
L'utilisation du module complémentaire conduit au crash de Home Assistant.
Le CPU et la mémoire sont anormalement sollicités (>80% CPU >60% RAM).
Cela conduit à un freeze du serveur HA et l'obligation de faire un hard reset
Merci

**Configuration**
cycle: 14400
debug: true
wipe_influxdb: false
home_assistant:
  enable: true
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: true
  hostname: a0d7b954-influxdb
  port: 8086
  token: 'myelectricaldata:PDL'
  org: '-'
  bucket: myelectricaldata/autogen
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: "XXXXXX"
  password: "XXXXXX"
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0
myelectricaldata:
  'XXXXXXXXXXXXX':
    enable: 'true'
    token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    name: Maison
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_hc: '0.13848'
    consumption_price_hp: '0.18594'
    offpeak_hours_0: 22H24-6H24
    offpeak_hours_1: 22H24-6H24
    offpeak_hours_2: 22H24-6H24
    offpeak_hours_3: 22H24-6H24
    offpeak_hours_4: 22H24-6H24
    offpeak_hours_5: 22H24-6H24
    offpeak_hours_6: 22H24-6H24
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    refresh_addresse: 'false'
    refresh_contract: 'false'

**Type d'installation**
Home Assistant 

**Version : 2022.11.5**

**Comment by m4dm4rtig4n** [comment]
Hello,

Tu sais me dire environ à quel moment de l'importation Home Assistant n'arrive plus à suivre la cadence ?

Lors de l'import InfluxDB, je passe par un mode d'importation "bulk" des data qui envoie énormement d'information en très de temps dans celui-ci.
A la maison j'ai une installation assez costaux donc ca passe sans soucis, mais si tu est sur un RPI ou autre ca peut effectivement engendrer des soucis.

Si c'est effectivement le cas, je vais voir pour réduire le nombre d'information que j'envoie en simultannées.

**Comment by geobar78** [comment]
Bonjour,
Je confirme même souci, effectivement RPI4, je le laisse tourner depuis une heure mais plus rien ne répond, quand à vous dire si c'est lors de l'import InfluxDB c'est difficile, le log c'était arrêté de mémoire à import ou export concuption puis daily, je n'ai pas eu l'idée de faire une copie d'écran désolé.

**Comment by m4dm4rtig4n** [comment]
Pouvez vous essayer de désactiver l'import vers l'influxdb pour tester ?
Il suffit de mettre enable: "false" dans le config.yaml et de relancer l'intégration.

**Comment by geobar78** [comment]
ça fonctionne
![1](https://user-images.githubusercontent.com/75928935/205271804-48bdb3a8-8d25-42bc-b426-1cacdf04fd5d.png)
![2](https://user-images.githubusercontent.com/75928935/205271842-2b9923a6-e197-4fd8-839e-b3c214029571.png)
![3](https://user-images.githubusercontent.com/75928935/205271868-1925daef-087b-4219-b959-4aa18dedcfa4.png)

**Comment by pbranly** [comment]
Impossible de dire si c'est lié mais j'ai eu 2 blocages de mon NUC depuis une semaine 
Obligation d'arrêter et de redémarrer 
Phil

**Comment by m4dm4rtig4n** [comment]
@geobar78 du coup plus de crash de HA ?

**Comment by geobar78** [comment]
Non plus de crash, une utilisation mémoire et cpu normale

**Comment by m4dm4rtig4n** [comment]
Ok merci pour ton retour je regarde ca, dans le pire des cas ca va mettre un peu plus de temps à importer.

**Comment by buddy31130** [comment]
Hello ! Merci pour ta réponse.
Je suis effectivement sur un RPi 4.
Et c'est au moment d'importer dans influxDB que ça plante. Même après une nuit, impossible de relancer l'application.
J'utilisais enedisgateway. J'aurais peut être dû utiliser la même base de donnée ?
Merci pour ton aide !

**Comment by geobar78** [comment]
@m4dm4rtig4n y a pas de quoi, c'est le minimum que je puisse faire, encore bravo pour ton super boulot ;-) que j'utilise depuis deux ans maintenant.

**Comment by HermesHonshappo** [comment]
Hello

Upgrade faite ce matin, et moi aussi, deux crash de HA, lorsqu'il était en train de populer influxdb
Pourtant c'est pas un Pi, mais un mini PC (avec un J3160 en CPU je crois), un SSD et 8Gb de RAM

Et le influxdb (v2) est sur mon NAS Synology, dans un docker, donc là non plus pas de souci de performance...

J'ai relancé 3 fois HA ce matin, avant de faire un fallback sur l'ancienne version. On voit les pics d'utilisation de CPU, mais surtout de la mémoire:

<img width="407" alt="Screenshot 2022-12-02 at 14 44 06" src="https://user-images.githubusercontent.com/97752752/205306614-2835135f-b163-4975-9e0e-032f2d1f14df.png">

Voilà des extraits du log
```2022-12-02 08:34:44.780 -     INFO :  Récupération des données : 2021-06-04 => 2021-06-11
2022-12-02 08:34:45.402 -     INFO :   => Toutes les données sont déjà en cache.
2022-12-02 08:34:45.406 -     INFO :  Récupération des données : 2021-06-04 => 2021-06-11
2022-12-02 08:34:45.406 -     INFO :   => Chargement des données depuis MyElectricalData 2021-06-04 => 2021-06-11
2022-12-02 08:34:46.031 -     INFO :   => Chargement des données depuis MyElectricalData 2021-06-04 => 2021-06-11
2022-12-02 08:34:51.185 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-02 08:34:51.186 -    ERROR : 
2022-12-02 08:34:51.186 -    ERROR :  Echec de la récupération des données.
2022-12-02 08:34:51.186 -    ERROR :   => no measure found for this usage point
2022-12-02 08:34:51.186 -    ERROR : 
2022-12-02 08:34:51.187 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-02 08:34:51.187 -     INFO :  Récupération des données : 2021-05-28 => 2021-06-04

═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-02 08:35:18.967 -     INFO :  Récupération des données : 2021-04-02 => 2021-04-09
2022-12-02 08:35:19.572 -     INFO :   => Chargement des données depuis MyElectricalData 2021-03-26 => 2021-04-02
2022-12-02 08:35:19.598 -     INFO :   => Chargement des données depuis MyElectricalData 2021-04-02 => 2021-04-09
2022-12-02 08:35:25.406 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-02 08:35:25.407 -    ERROR : 
2022-12-02 08:35:25.407 -    ERROR :  Echec de la récupération des données.
2022-12-02 08:35:25.407 -    ERROR :   => no measure found for this usage point
2022-12-02 08:35:25.407 -    ERROR : 
2022-12-02 08:35:25.407 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════

2022-12-02 08:48:37.575 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-02 08:48:37.576 -     INFO : ▌│█║▌║▌║       ___                                 _     _____  _         _       _      _  _  _       ║▌║▌║█│▌
2022-12-02 08:48:37.576 -     INFO : ▌│█║▌║▌║      |_ _| _ __ ___   _ __    ___   _ __ | |_  |  ___|(_) _ __  (_) ___ | |__  | || || |      ║▌║▌║█│▌
2022-12-02 08:48:37.576 -     INFO : ▌│█║▌║▌║       | | | '_ ` _ \ | '_ \  / _ \ | '__|| __| | |_   | || '_ \ | |/ __|| '_ \ | || || |      ║▌║▌║█│▌
2022-12-02 08:48:37.576 -     INFO : ▌│█║▌║▌║       | | | | | | | || |_) || (_) || |   | |_  |  _|  | || | | || |\__ \| | | ||_||_||_|      ║▌║▌║█│▌
2022-12-02 08:48:37.577 -     INFO : ▌│█║▌║▌║      |___||_| |_| |_|| .__/  \___/ |_|    \__| |_|    |_||_| |_||_||___/|_| |_|(_)(_)(_)      ║▌║▌║█│▌
2022-12-02 08:48:37.577 -     INFO : ▌│█║▌║▌║                      |_|                                                                      ║▌║▌║█│▌
2022-12-02 08:48:37.577 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Exception ignored in: <function InfluxDBClient.__del__ at 0x7ff24df530d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/influxdb_client.py", line 319, in __del__
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 84, in __del__
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 661, in _signout
TypeError: 'NoneType' object is not callable
[08:48:55] FATAL: The app has crashed. Are you sure you entered the correct config options?






2022-12-02 08:51:27.908 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-02 08:51:27.908 -     INFO :  [25985962368507] RÉCUPÉRATION DE LA CONSOMMATION JOURNALIÈRE :
2022-12-02 08:51:27.908 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-02 08:51:27.923 -     INFO :  Récupération des données : 2022-10-27 => 2022-12-02
2022-12-02 08:51:28.837 -     INFO :   => Toutes les données sont déjà en cache.
2022-12-02 08:51:28.838 -     INFO :  Récupération des données : 2022-08-16 => 2022-09-21
2022-12-02 08:51:28.872 -     INFO :   => Chargement des données depuis MyElectricalData 2022-10-27 => 2022-12-02
2022-12-02 08:51:29.729 -     INFO :   => Toutes les données sont déjà en cache.
2022-12-02 08:51:29.729 -     INFO :  Récupération des données : 2022-07-11 => 2022-08-16
2022-12-02 08:51:30.154 -    ERROR : Multiple rows were found when one or none was required
Traceback (most recent call last):
  File "/app/models/query_daily.py", line 70, in run
    self.db.insert_daily(
  File "/app/models/database.py", line 590, in insert_daily
    daily = self.session.scalars(query).one_or_none()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1464, in one_or_none
    return self._only_one_row(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 614, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required
2022-12-02 08:51:30.163 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-02 08:51:30.163 -    ERROR : 
2022-12-02 08:51:30.164 -    ERROR :  Multiple rows were found when one or none was required
2022-12-02 08:51:30.164 -    ERROR : 
2022-12-02 08:51:30.164 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by m4dm4rtig4n** [comment]
Avec la v0.8.6, je vais proposer d'activer l'importation InfluxDB en mode "SYNCHRONOUS" ou "ASYNCHRONOUS".
Actuellement j'importe en mode "ASYNCHRONOUS" ce qui génére une forte charge CPU & RAM.

Par défaut, ce sera le mode "SYNCHRONOUS".

**Comment by m4dm4rtig4n** [comment]
La v0.8.6 à pop, je veut bien que l'un de vous refait un test :)

**Comment by geobar78** [comment]
La maj n'apparaît pas encore chez moi mais dès que je te fais un retour.

**Comment by geobar78** [comment]
HAAAA le dev ;-) le boulet

**Comment by geobar78** [comment]
Par contre que ce soit la dev ou la normale je suis en v0.8.3 normal ?

**Comment by geobar78** [comment]
Donc si j'ai bien compris dans config.yalm j'ajoute write_options: "SYNCHRONOUS" sous influxdb et enable = true
J'attend plus que le feu vert pour savoir si j'ai la bonne version dev ou pas.

**Comment by m4dm4rtig4n** [comment]
Faut passer en 0.8.6-dev minimun.
De passe je suis en mode SYNCHRONOUS :
https://github.com/m4dm4rtig4n/myelectricaldata/blob/4e040b265844ad2c8030d4b0e7bf82a0ce421b80/config.exemple.yaml#L18

**Comment by geobar78** [comment]
Voilà v.0.8.6 c'est testé, ça tourne bien

**Comment by geobar78** [comment]
Ça tape quand même sauvagement dans la mémoire et le pross mais ça crash pas.

**Comment by geobar78** [comment]
J'ai parlé trop vite, j'ai commencé par perdre le supervisor puis HA. pourtant les logs d'exportations dans influx semblaient laisser penser que ça allait bien.

**Comment by geobar78** [comment]
Je pense savoir pourquoi, comme tu m'as dit qu'on était de base en synchronus je n'ai pas ajouté la ligne 18 au fichier config....
mais je pense que la ligne est nécessaire

**Comment by geobar78** [comment]
Bon même après ajout de la ligne 18, crash de HA lors de l'exportation de consuption_détail dans influx db. J'ai vu le pross monter à 70% la mémoire à 86% et ensuite crash

**Comment by m4dm4rtig4n** [comment]
Non la ligne 18 n'est pas obligatoire, le mode SYNCHRONE est le mode qui consomme le moins et activé par défaut.

**Comment by geobar78** [comment]
Alors Huston nous avons un problème :-D

**Comment by m4dm4rtig4n** [comment]
Sur la 0.8.8-dev ,j'ai activer le mode "batching" qui permet de configurer plus finement l'importation :
https://github.com/m4dm4rtig4n/myelectricaldata/blob/dca361ddc84e25c7d5683d5c3f4010cca6434f2e/config.exemple.yaml#L17

Si tu veut le tester, il fait mettre `method: batching` et ensuite libre à toi de tuner les `batching_options` sachant qu'actuellement c'est les valeurs par défauts.

**Comment by geobar78** [comment]
Il semble que toutes ces options concernent influxdb v2.0 sauf que dans mon cas je suis en influxdb : Chronograf Version: 1.9.4
je regarde comment passer en v2 sur HA ou la commande équivalente pour la v1 car j'utilise graphana

**Comment by geobar78** [comment]
Alors pour tout dire je ne trouve même pas le moyen de connaître ma version de influxdb... j'utilise l'addon officiel https://github.com/hassio-addons/addon-influxdb/blob/main/README.md

**Comment by pbranly** [comment]
Hello
Si tu dois utiliser chronograf c’est que tu es en 1.x. Dans la version 2.x chronograf est intégré …… dans les grandes lignes 
Phil

**Comment by geobar78** [comment]
Merci @pbranly 
sur la doc ils parlent d'api retro compatible je ne sais pas si l'option batching rentre là dedans.

https://github.com/influxdata/influxdb-client-python#influxdb-18-api-compatibility

**Comment by geobar78** [comment]
La façon la plus simple de savoir et de tester :-D 
J'ai mis ça comme valeur:

  batching_options:
    batch_size: 100
    flush_interval: 10000
    jitter_interval: 2
    retry_interval: 50000
    max_retry_time: 180_0000
    max_retries: 5
    max_retry_delay: 125_0000
    exponential_base: 5

**Comment by geobar78** [comment]
hummm
J'ai ça en fin de log

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: usage_points.consentement_expiration
[SQL: SELECT usage_points.usage_point_id, usage_points.name, usage_points.cache, usage_points.consumption, usage_points.consumption_detail, usage_points.production, usage_points.production_detail, usage_points.consumption_price_base, usage_points.consumption_price_hc, usage_points.consumption_price_hp, usage_points.production_price, usage_points.offpeak_hours_0, usage_points.offpeak_hours_1, usage_points.offpeak_hours_2, usage_points.offpeak_hours_3, usage_points.offpeak_hours_4, usage_points.offpeak_hours_5, usage_points.offpeak_hours_6, usage_points."plan", usage_points.refresh_addresse, usage_points.refresh_contract, usage_points.token, usage_points.progress, usage_points.progress_status, usage_points.enable, usage_points.consentement_expiration, usage_points.call_number, usage_points.quota_reached, usage_points.quota_limit, usage_points.quota_reset_at, usage_points.last_call, usage_points.ban, usage_points.consumption_max_date, usage_points.consumption_detail_max_date, usage_points.production_max_date, usage_points.production_detail_max_date 
FROM usage_points 
WHERE usage_points.usage_point_id = ?]
[parameters: ('25256439806760',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[08:24:46] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by geobar78** [comment]
pas sûr que ce soit lié à l'export influxdb, l'ancienne version de mémoire me faisait pareil quand je lançais l'app trop tôt dans la journée, j'avais pris l'habitude de la démarrer après 17h

**Comment by geobar78** [comment]
Alors ça bug mais je ne pense pas qu'il arrive jusqu'à l'export influx

2022-12-03 09:10:14.586 -     INFO :  Check config.yaml :
2022-12-03 09:10:14.587 -     INFO :   => Config valid
2022-12-03 09:10:14.604 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-03 09:10:14.604 -     INFO :  LOADING CONFIGURATION...
2022-12-03 09:10:14.605 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-03 09:10:14.605 -     INFO :  25256439806760
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: usage_points.consentement_expiration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/main.py", line 46, in <module>
    DB.set_usage_point(usage_point_id, data)
  File "/app/models/database.py", line 205, in set_usage_point
    usage_points = self.session.scalars(query).one_or_none()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: usage_points.consentement_expiration
[SQL: SELECT usage_points.usage_point_id, usage_points.name, usage_points.cache, usage_points.consumption, usage_points.consumption_detail, usage_points.production, usage_points.production_detail, usage_points.consumption_price_base, usage_points.consumption_price_hc, usage_points.consumption_price_hp, usage_points.production_price, usage_points.offpeak_hours_0, usage_points.offpeak_hours_1, usage_points.offpeak_hours_2, usage_points.offpeak_hours_3, usage_points.offpeak_hours_4, usage_points.offpeak_hours_5, usage_points.offpeak_hours_6, usage_points."plan", usage_points.refresh_addresse, usage_points.refresh_contract, usage_points.token, usage_points.progress, usage_points.progress_status, usage_points.enable, usage_points.consentement_expiration, usage_points.call_number, usage_points.quota_reached, usage_points.quota_limit, usage_points.quota_reset_at, usage_points.last_call, usage_points.ban, usage_points.consumption_max_date, usage_points.consumption_detail_max_date, usage_points.production_max_date, usage_points.production_detail_max_date 
FROM usage_points 
WHERE usage_points.usage_point_id = ?]
[parameters: ('25256439806760',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[09:10:15] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by buddy31130** [comment]
Bonjour,
avec l'application MyElectricalData version: 0.8.8-dev, j'ai les mêmes erreurs que geobar78.
Avec l'application MyElectricalData Dev version: 0.8.8-dev, je n'ai plus d'erreur. Les données sont bien ajoutées dans influxDB.

**Comment by geobar78** [comment]
@buddy31130 salut, tu as mis quoi comme config influxdb du fichier config ? je vais mettre comme toi et faire l'essai avec la version dev

**Comment by buddy31130** [comment]
j'ai mis ça : 

`cycle: 14400
debug: true
wipe_influxdb: false
home_assistant:
  enable: true
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: true
  hostname: a0d7b954-influxdb
  port: 8086
  token: 'XXXXXX:YYYYYY'
  org: '-'
  bucket: myelectricaldata/autogen
  method: asynchronous
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: "XXXXXX"
  password: "XXXXXXXX"
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0
myelectricaldata:
  'XXXXXXXXX':
    enable: 'true'
    token: "XXXXXXXXX"
    name: Maison
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_hc: '0.13848'
    consumption_price_hp: '0.18594'
    offpeak_hours_0: 22H24-6H24
    offpeak_hours_1: 22H24-6H24
    offpeak_hours_2: 22H24-6H24
    offpeak_hours_3: 22H24-6H24
    offpeak_hours_4: 22H24-6H24
    offpeak_hours_5: 22H24-6H24
    offpeak_hours_6: 22H24-6H24
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    refresh_addresse: 'false'
    refresh_contract: 'false'
`

**Comment by geobar78** [comment]
@buddy31130 ok asynchronous je test

**Comment by geobar78** [comment]
Bien de mon coté je n'arrive pas à lancer MyElectricalData Dev, j'ai essayé de modifier le config.yalm, de le supprimer pour en avoir un tout neuf puis de le remplir mais idem :

[11:41:00] INFO: Using config file found in /config/enedisgateway2mqtt_dev/config.yaml
/config/enedisgateway2mqtt_dev/config.yaml
  49:30     error    trailing spaces  (trailing-spaces)
  75:1      error    trailing spaces  (trailing-spaces)
  76:1      error    trailing spaces  (trailing-spaces)
[11:41:08] FATAL: Config file has an invalid yaml format. Please check the file in /config/enedisgateway2mqtt_dev/config.yaml. Errors list above. You can check yaml validity with the online tool yamllint.com
/etc/cont-init.d/99-run.sh: exiting 1

**Comment by buddy31130** [comment]
@geobar78 as tu utilisé l'application "MyElectricalData Dev" et non pas la "MyElectricalData" ?

**Comment by geobar78** [comment]
@buddy31130 oui le dernier rapport c'est bien avec MyElectricalData Dev

**Comment by geobar78** [comment]
Ayé j'ai trouvé dans la config de MyElectricalData Dev j'ai enlevé _dev pour le nom du dossier contenant config... en gros il va chercher le même config que MyElectricalData et là ça tourne. je sais pas encore si HA va tenir

**Comment by geobar78** [comment]
Alors au final avec MyElectricalData Dev + Influxdb réglé en synchronus, récupération de quelques données utilisations ram et cpu normale et pas de crash HA, @m4dm4rtig4n j'espère que je ne t'ai pas fait perdre du temps sur le batching en pensant que j'utilisais la version Dev alors que j'utilisais la version normale (les deux me proposant une mise à jour en v.8.x à chaque fois je ne pensais pas qu'il y avait une différence) ...

**Comment by m4dm4rtig4n** [comment]
@geobar78 pas de soucis au moins ca fait une fonctionnalité en plus pour les utilisateurs 🗡️
