### ISSUE TITLE
[BUG] - Problème d'import dans influxdb si la durée de rétention est inférieure à la date la plus lointaine dans la base

### ISSUE THREAD

**Issue by evenisse** [m4dm4rtig4n/myelectricaldata#164]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Si un bucket est configuré avec une durée de rétention plus courte que la date la plus lointaine présente dans la base, l'import génère une exception qui bloque la suite du traitement

```
Traceback (most recent call last):
  File "/app/models/jobs.py", line 171, in job_import_data
    ExportInfluxDB(self.usage_point_id).daily(
  File "/app/models/export_influxdb.py", line 34, in daily
    app.INFLUXDB.write(
  File "/app/models/influxdb.py", line 90, in write
    self.write_api.write(bucket=self.bucket, org=self.org, record=record)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 374, in write
    results = list(map(write_payload, payloads.items()))
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 372, in write_payload
    return self._post_write(_async_req, bucket, org, final_string, payload[0])
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 483, in _post_write
    return self._write_service.post_write(org=org, bucket=bucket, body=body, precision=precision,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 60, in post_write
    (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 90, in post_write_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.5.1', 'X-Platform-Error-Code': 'unprocessable entity', 'Date': 'Fri, 02 Dec 2022 21:55:31 GMT', 'Content-Length': '135'})
HTTP response body: {"code":"unprocessable entity","message":"failure writing points to database: partial write: points beyond retention policy dropped=1"}
```

**Configuration**
Il me faut la partie enedis_gateway de votre config.yml, sans les PDL et Token.

**Type d'installation**
Docker

**Version : 0.8.7**

**Comment by m4dm4rtig4n** [comment]
Ah, c'est génant :D

**Comment by m4dm4rtig4n** [comment]
Je viens de tester chez moi et ca ne bloque par l'import pour le coup.
Il spam comme quoi il n'arrive pas à ecrire sur les date en questions, mais continue.

**Comment by evenisse** [comment]
OK, j'ai dû faire une analyse trop rapide.

**Comment by m4dm4rtig4n** [comment]
Bah la j'ai trouver le moyen d'allez récupéré la durée de rétention du bucket sur l'influxdb.
Je verrais pour allez check celle-ci avant d'importer et éviter d'avoir l'erreur dans les logs.

**Comment by m4dm4rtig4n** [comment]
Voila plus d'erreur et un WARNING au démarrage :
![image](https://user-images.githubusercontent.com/7872518/205695153-e1cf90c6-aa96-4cf6-b4a7-647de00e307d.png)

**Comment by m4dm4rtig4n** [comment]
Ca arrivera avec la 0.8.8.
