### ISSUE TITLE
[BUG] - Migration en erreur - App has crashed

### ISSUE THREAD

**Issue by floow77** [m4dm4rtig4n/myelectricaldata#168]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Migration vers myelectricaldata

2022-12-03 06:10:11.281 -     INFO :  Check config.yaml :
2022-12-03 06:10:11.281 -     INFO :   => Config valid
2022-12-03 06:10:11.297 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-03 06:10:11.298 -     INFO :  LOADING CONFIGURATION...
2022-12-03 06:10:11.298 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-03 06:10:11.298 -     INFO :  22149782812123
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: usage_points.consentement_expiration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/main.py", line 46, in <module>
    DB.set_usage_point(usage_point_id, data)
  File "/app/models/database.py", line 205, in set_usage_point
    usage_points = self.session.scalars(query).one_or_none()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: usage_points.consentement_expiration
[SQL: SELECT usage_points.usage_point_id, usage_points.name, usage_points.cache, usage_points.consumption, usage_points.consumption_detail, usage_points.production, usage_points.production_detail, usage_points.consumption_price_base, usage_points.consumption_price_hc, usage_points.consumption_price_hp, usage_points.production_price, usage_points.offpeak_hours_0, usage_points.offpeak_hours_1, usage_points.offpeak_hours_2, usage_points.offpeak_hours_3, usage_points.offpeak_hours_4, usage_points.offpeak_hours_5, usage_points.offpeak_hours_6, usage_points."plan", usage_points.refresh_addresse, usage_points.refresh_contract, usage_points.token, usage_points.progress, usage_points.progress_status, usage_points.enable, usage_points.consentement_expiration, usage_points.call_number, usage_points.quota_reached, usage_points.quota_limit, usage_points.quota_reset_at, usage_points.last_call, usage_points.ban, usage_points.consumption_max_date, usage_points.consumption_detail_max_date, usage_points.production_max_date, usage_points.production_detail_max_date 
FROM usage_points 
WHERE usage_points.usage_point_id = ?]
[parameters: ('22149782812123',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
**[06:10:11] FATAL: The app has crashed. Are you sure you entered the correct config options?**

**Configuration**
cycle: 14400 # 4H
debug: true
wipe_influxdb: false
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: true
  hostname: a0d7b954-influxdb
  port: 8086
  token: toto:toto
  org: "-"
  bucket: "DATABASE/RETENTION"
  asynchronous: "false"
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: "flotest"
  password: "flotest"
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0
myelectricaldata:
  "22149782812123":
    enable: "true"
    token: 2T2222TOKENTEST
    name: "Maison"
    addresses: "true"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_price_base: "0.1679" 
    consumption_price_hc: "0.1422" 
    consumption_price_hp: "0.1769" 
    consumption_max_date: "2021-07-03"
    consumption_detail_max_date: "2021-07-03"
    offpeak_hours_0: 01H36-8H06;12H06-13H36 # LUNDI
    offpeak_hours_1: 01H36-8H06;12H06-13H36 # MARDI
    offpeak_hours_2: 01H36-8H06;12H06-13H36 # MERCREDI
    offpeak_hours_3: 01H36-8H06;12H06-13H36 # JEUDI
    offpeak_hours_4: 01H36-8H06;12H06-13H36 # VENDREDI
    offpeak_hours_5: 01H36-8H06;12H06-13H36 # SAMEDI
    offpeak_hours_6: 01H36-8H06;12H06-13H36 # DIMANCHE
    plan: HC/HP
    production: "false"
    production_detail: "false"
    production_price: "0.0"
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: "false"
    refresh_contract: "false"

**Type d'installation**
HassIO

**Version : 0.8.8-dev *

**Comment by jaroslawp** [comment]
For me above happens when starting the addon without pre-existing enedisgateway.db. If I start it with already existing file from previous add-on version it also crashes with this error:

```
[08:21:35] INFO: Starting the app
 
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 0c07baa8d7b2, base

[...]

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table config already exists
[SQL: 
CREATE TABLE config (
	"key" TEXT NOT NULL, 
	value TEXT NOT NULL, 
	PRIMARY KEY ("key")
)
]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-12-03 08:21:38.883 -  WARNING : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ▲ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-03 08:21:38.885 -  WARNING :  MIGRATION DE L'ANCIENNE BASE DE DONNÉES VERS LA NOUVELLE STRUCTURE.
2022-12-03 08:21:38.885 -  WARNING : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ▲ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by Pascal66** [comment]
Mêmes problèmes que les deux ci-dessus, avec ou sans la base de données

**Comment by Pascal66** [comment]
Je viens de lancer, avec et sans base, la version-dev, qui elle fonctionne parfaitement dans les deux cas.

**Comment by jaroslawp** [comment]
The dev version starts for me but there are errors on execution:
```
2022-12-03 09:18:54.107 -     INFO :  Récupération des données : 2022-10-27 => 2022-12-02
2022-12-03 09:18:54.820 -     INFO :   => Chargement des données depuis MyElectricalData 2022-10-27 => 2022-12-02
2022-12-03 09:18:55.975 -    ERROR : Multiple rows were found when one or none was required
Traceback (most recent call last):
  File "/app/models/query_daily.py", line 74, in run
    self.db.insert_daily(
  File "/app/models/database.py", line 660, in insert_daily
    daily = self.session.scalars(query).one_or_none()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1464, in one_or_none
    return self._only_one_row(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 614, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required
```
and:
```
Traceback (most recent call last):
  File "/app/models/jobs.py", line 80, in job_import_data
    self.get_consumption()
  File "/app/models/jobs.py", line 252, in get_consumption
    result = Daily(
  File "/app/models/query_daily.py", line 137, in get
    app.LOG.error(error)
UnboundLocalError: local variable 'error' referenced before assignment
```
.. but then subsequent calls seem to work OK.

**Comment by m4dm4rtig4n** [comment]
> The dev version starts for me but there are errors on execution:
> 
> ```
> 2022-12-03 09:18:54.107 -     INFO :  Récupération des données : 2022-10-27 => 2022-12-02
> 2022-12-03 09:18:54.820 -     INFO :   => Chargement des données depuis MyElectricalData 2022-10-27 => 2022-12-02
> 2022-12-03 09:18:55.975 -    ERROR : Multiple rows were found when one or none was required
> Traceback (most recent call last):
>   File "/app/models/query_daily.py", line 74, in run
>     self.db.insert_daily(
>   File "/app/models/database.py", line 660, in insert_daily
>     daily = self.session.scalars(query).one_or_none()
>   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1464, in one_or_none
>     return self._only_one_row(
>   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 614, in _only_one_row
>     raise exc.MultipleResultsFound(
> sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required
> ```
> 
> and:
> 
> ```
> Traceback (most recent call last):
>   File "/app/models/jobs.py", line 80, in job_import_data
>     self.get_consumption()
>   File "/app/models/jobs.py", line 252, in get_consumption
>     result = Daily(
>   File "/app/models/query_daily.py", line 137, in get
>     app.LOG.error(error)
> UnboundLocalError: local variable 'error' referenced before assignment
> ```
> 
> .. but then subsequent calls seem to work OK.

C'est le même soucis que sur le ticket https://github.com/m4dm4rtig4n/myelectricaldata/issues/143
Je doit refaire une passe sur cette partie.

**Comment by m4dm4rtig4n** [comment]
Résolu sur le forum HACF.

**Comment by Pascal66** [comment]
> Résolu sur le forum HACF.

Pourrais tu mettre le lien vers la résolution sur le forum HACF s'il te plait ?
