### ISSUE TITLE
[BUG] - several influx errors in log

### ISSUE THREAD

**Issue by pbranly** [m4dm4rtig4n/myelectricaldata#179]
Hi
I have this long list of errors during the export to influx 

06/12/2022 21:25:52
2022-12-06 21:25:52.178 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
06/12/2022 21:25:52
2022-12-06 21:25:52.263 -     INFO :   - 2022-12
06/12/2022 21:25:52
Traceback (most recent call last):
06/12/2022 21:25:52
  File "/app/models/jobs.py", line 171, in job_import_data
06/12/2022 21:25:52
    ExportInfluxDB(self.usage_point_id).daily(
06/12/2022 21:25:52
  File "/app/models/export_influxdb.py", line 34, in daily
06/12/2022 21:25:52
    app.INFLUXDB.write(
06/12/2022 21:25:52
  File "/app/models/influxdb.py", line 162, in write
06/12/2022 21:25:52
    self.write_api.write(bucket=self.bucket, org=self.org, record=record)
06/12/2022 21:25:52
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 374, in write
06/12/2022 21:25:52
    results = list(map(write_payload, payloads.items()))
06/12/2022 21:25:52
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 372, in write_payload
06/12/2022 21:25:52
    return self._post_write(_async_req, bucket, org, final_string, payload[0])
06/12/2022 21:25:52
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 483, in _post_write
06/12/2022 21:25:52
    return self._write_service.post_write(org=org, bucket=bucket, body=body, precision=precision,
06/12/2022 21:25:52
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 60, in post_write
06/12/2022 21:25:52
    (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
06/12/2022 21:25:52
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 90, in post_write_with_http_info
06/12/2022 21:25:52
    return self.api_client.call_api(
06/12/2022 21:25:52
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
06/12/2022 21:25:52
    return self.__call_api(resource_path, method,
06/12/2022 21:25:52
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
06/12/2022 21:25:52
    response_data = self.request(
06/12/2022 21:25:52
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
06/12/2022 21:25:52
    return self.rest_client.POST(url,
06/12/2022 21:25:52
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
06/12/2022 21:25:52
    return self.request("POST", url,
06/12/2022 21:25:52
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request
06/12/2022 21:25:52
    raise ApiException(http_resp=r)
06/12/2022 21:25:52
influxdb_client.rest.ApiException: (422)
06/12/2022 21:25:52
Reason: Unprocessable Entity
06/12/2022 21:25:52
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.5.1', 'X-Platform-Error-Code': 'unprocessable entity', 'Date': 'Tue, 06 Dec 2022 20:25:52 GMT', 'Content-Length': '221'})
06/12/2022 21:25:52
HTTP response body: {"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \"Wh\" on measurement \"consumption\" is type float, already exists as type integer dropped=1"}
06/12/2022 21:25:52
06/12/2022 21:25:52
2022-12-06 21:25:52.311 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
06/12/2022 21:25:52
2022-12-06 21:25:52.312 -    ERROR : 
06/12/2022 21:25:52
2022-12-06 21:25:52.312 -    ERROR :  Erreur lors de l'exportation des données dans InfluxDB
06/12/2022 21:25:52
2022-12-06 21:25:52.312 -    ERROR :  (422)
06/12/2022 21:25:52
Reason: Unprocessable Entity
06/12/2022 21:25:52
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.5.1', 'X-Platform-Error-Code': 'unprocessable entity', 'Date': 'Tue, 06 Dec 2022 20:25:52 GMT', 'Content-Length': '221'})
06/12/2022 21:25:52
HTTP response body: {"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \"Wh\" on measurement \"consumption\" is type float, already exists as type integer dropped=1"}

**Comment by m4dm4rtig4n** [comment]
Ce message d'erreur n'est en theorie plus possible si tu as une base influxdb reset depuis la dernière 0.8.8-dev...

**Comment by vingerha** [comment]
Je confirme que mon export de 088 vers influx est sans soucis

**Comment by pbranly** [comment]
Avec la version de minuit chargée ce matin, il y a encore de erreurs influx 

08/12/2022 6:18:01
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.5.1', 'X-Platform-Error-Code': 'unprocessable entity', 'Date': 'Thu, 08 Dec 2022 05:18:01 GMT', 'Content-Length': '221'})
08/12/2022 6:18:01
HTTP response body: {"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \"Wh\" on measurement \"consumption\" is type float, already exists as type integer dropped=1"}

je reset la base influx et je compléterai 

phil
