### ISSUE TITLE
[BUG] - Exception NOT NULL constraint

### ISSUE THREAD

**Issue by evenisse** [m4dm4rtig4n/myelectricaldata#180]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Lors de l'init de l'import, il y a eu une exception : 

```
2022-12-07 01:11:23.395 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-07 01:11:23.395 -     INFO :  [XXXXXXXXXXXXX] RÉCUPÉRATION DE LA CONSOMMATION JOURNALIÈRE :
2022-12-07 01:11:23.395 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-07 01:11:23.558 -     INFO :  Récupération des données : 2022-11-01 => 2022-12-07
2022-12-07 01:11:23.735 -     INFO :   => Chargement des données depuis MyElectricalData 2022-11-01 => 2022-12-07
2022-12-07 01:11:29.789 -     INFO :  Récupération des données : 2022-09-26 => 2022-11-01
2022-12-07 01:11:29.800 -    ERROR : (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) NOT NULL constraint failed: consumption_daily.id
[SQL: INSERT INTO consumption_daily (usage_point_id, date, value, blacklist, fail_count) VALUES (?, ?, ?, ?, ?)]
[parameters: ('XXXXXXXXXXXXX', '2022-12-06 00:00:00.000000', 0, 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: consumption_daily.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/models/query_daily.py", line 53, in run
    current_data = self.db.get_daily(self.usage_point_id, begin, end, self.measure_type)
  File "/app/models/database.py", line 750, in get_daily
    query_result = self.get_daily_date(usage_point_id, checkDate, measurement_direction)
  File "/app/models/database.py", line 604, in get_daily_date
    return self.session.scalars(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1660, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2257, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2246, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3526, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) NOT NULL constraint failed: consumption_daily.id
[SQL: INSERT INTO consumption_daily (usage_point_id, date, value, blacklist, fail_count) VALUES (?, ?, ?, ?, ?)]
[parameters: ('XXXXXXXXXXXXX', '2022-12-06 00:00:00.000000', 0, 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-07 01:11:29.801 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-07 01:11:29.802 -    ERROR : 
2022-12-07 01:11:29.802 -    ERROR :  (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) NOT NULL constraint failed: consumption_daily.id
[SQL: INSERT INTO consumption_daily (usage_point_id, date, value, blacklist, fail_count) VALUES (?, ?, ?, ?, ?)]
[parameters: ('XXXXXXXXXXXXX', '2022-12-06 00:00:00.000000', 0, 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-07 01:11:29.802 -    ERROR : 
2022-12-07 01:11:29.802 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
Traceback (most recent call last):
  File "/app/models/jobs.py", line 80, in job_import_data
    self.get_consumption()
  File "/app/models/jobs.py", line 252, in get_consumption
    result = Daily(
  File "/app/models/query_daily.py", line 138, in get
    app.LOG.error(error)
UnboundLocalError: local variable 'error' referenced before assignment
2022-12-07 01:11:29.802 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-07 01:11:29.803 -    ERROR : 
2022-12-07 01:11:29.803 -    ERROR :  Erreur lors de la récupération de votre consommation journalière
2022-12-07 01:11:29.803 -    ERROR :  local variable 'error' referenced before assignment
2022-12-07 01:11:29.803 -    ERROR : 
2022-12-07 01:11:29.803 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Configuration**
Il me faut la partie enedis_gateway de votre config.yml, sans les PDL et Token.

**Type d'installation**
Docker

**Version : 0.8.8-dev**

**Comment by evenisse** [comment]
Oui je l'avais supprimé. Je pourrai refaire un test ce soir si tu veux pour vérifier

**Comment by evenisse** [comment]
Je confirme. Je viens de refaire le tests, j'ai tout viré et j'ai eu l'exception.

**Comment by m4dm4rtig4n** [comment]
C'est bon j'ai trouver le soucis, le fix sortira avec la 0.8.8 :)
