### ISSUE TITLE
[HELP] - the app has crashed

### ISSUE THREAD

**Issue by buchnoun** [m4dm4rtig4n/myelectricaldata#183]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description de la fonctionnalité**
A chaque démarrage de l'application j'obtiens le log plus bas... J'ai effectué la migration depuis enedisgateway tenté de purger le cache... je ne suis pas expert je ne comprends pas où est l'erreur.
Merci d'avance pour votre aide

**Type d'installation**
Homeassistant via HACS

**Version : 0.8.7**

2022-12-07 12:12:32.827 -     INFO :    wipe_cache: True
2022-12-07 12:12:32.827 -     INFO :    home_assistant:
2022-12-07 12:12:32.828 -     INFO :      enable: True
2022-12-07 12:12:32.828 -     INFO :      discovery: True
2022-12-07 12:12:32.829 -     INFO :      discovery_prefix: homeassistant
2022-12-07 12:12:32.829 -     INFO :    influxdb:
2022-12-07 12:12:32.830 -     INFO :      enable: False
2022-12-07 12:12:32.830 -     INFO :      hostname: influxdb
2022-12-07 12:12:32.830 -     INFO :      port: 8086
2022-12-07 12:12:32.831 -     INFO :      token: ** hidden **
2022-12-07 12:12:32.831 -     INFO :      org: myelectricaldata
2022-12-07 12:12:32.832 -     INFO :      bucket: myelectricaldata
2022-12-07 12:12:32.832 -     INFO :      asynchronous: false
2022-12-07 12:12:32.833 -     INFO :    mqtt:
2022-12-07 12:12:32.833 -     INFO :      enable: True
2022-12-07 12:12:32.834 -     INFO :      hostname: 192.168.1.60
2022-12-07 12:12:32.834 -     INFO :      port: 1883
2022-12-07 12:12:32.835 -     INFO :      username: addons
2022-12-07 12:12:32.835 -     INFO :      password: ** hidden **
2022-12-07 12:12:32.835 -     INFO :      prefix: myelectricaldata
2022-12-07 12:12:32.836 -     INFO :      client_id: myelectricaldata
2022-12-07 12:12:32.836 -     INFO :      retain: True
2022-12-07 12:12:32.837 -     INFO :      qos: 0
2022-12-07 12:12:32.837 -     INFO :    myelectricaldata:
2022-12-07 12:12:32.837 -     INFO :      19362083904561:
2022-12-07 12:12:32.838 -     INFO :        enable: true
2022-12-07 12:12:32.838 -     INFO :        token: ** hidden **
2022-12-07 12:12:32.839 -     INFO :        name: LaChapelle
2022-12-07 12:12:32.839 -     INFO :        addresses: true
2022-12-07 12:12:32.840 -     INFO :        cache: true
2022-12-07 12:12:32.840 -     INFO :        consumption: true
2022-12-07 12:12:32.841 -     INFO :        consumption_detail: true
2022-12-07 12:12:32.841 -     INFO :        consumption_price_base: 0.1781
2022-12-07 12:12:32.841 -     INFO :        consumption_price_hc: 0.1410
2022-12-07 12:12:32.842 -     INFO :        consumption_price_hp: 0.17815
2022-12-07 12:12:32.842 -     INFO :        consumption_max_date: 2022-09-01
2022-12-07 12:12:32.843 -     INFO :        consumption_detail_max_date: 2022-09-01
2022-12-07 12:12:32.843 -     INFO :        offpeak_hours_0: 01H00-7H00;15H00-17H00
2022-12-07 12:12:32.843 -     INFO :        offpeak_hours_1: 01H00-7H00;15H00-17H00
2022-12-07 12:12:32.844 -     INFO :        offpeak_hours_2: 01H00-7H00;15H00-17H00
2022-12-07 12:12:32.845 -     INFO :        offpeak_hours_3: 01H00-7H00;15H00-17H00
2022-12-07 12:12:32.845 -     INFO :        offpeak_hours_4: 01H00-7H00;15H00-17H00
2022-12-07 12:12:32.845 -     INFO :        offpeak_hours_5: 01H00-7H00;15H00-17H00
2022-12-07 12:12:32.846 -     INFO :        offpeak_hours_6: 01H00-7H00;15H00-17H00
2022-12-07 12:12:32.846 -     INFO :        plan: HC/HP
2022-12-07 12:12:32.847 -     INFO :        production: false
2022-12-07 12:12:32.847 -     INFO :        production_detail: false
2022-12-07 12:12:32.848 -     INFO :        production_price: 0.0
2022-12-07 12:12:32.848 -     INFO :        production_max_date: 2021-06-01
2022-12-07 12:12:32.848 -     INFO :        production_detail_max_date: 2021-06-01
2022-12-07 12:12:32.849 -     INFO :        refresh_addresse: false
2022-12-07 12:12:32.850 -     INFO :        refresh_contract: false
2022-12-07 12:12:32.850 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-07 12:12:32.850 -     INFO :  Check config.yaml :
2022-12-07 12:12:32.851 -     INFO :   => Config valid
2022-12-07 12:12:32.870 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-07 12:12:32.871 -     INFO :  LOADING CONFIGURATION...
2022-12-07 12:12:32.871 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-07 12:12:32.871 -     INFO :  19362083904561
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: usage_points.consentement_expiration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/main.py", line 46, in <module>
    DB.set_usage_point(usage_point_id, data)
  File "/app/models/database.py", line 205, in set_usage_point
    usage_points = self.session.scalars(query).one_or_none()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: usage_points.consentement_expiration
[SQL: SELECT usage_points.usage_point_id, usage_points.name, usage_points.cache, usage_points.consumption, usage_points.consumption_detail, usage_points.production, usage_points.production_detail, usage_points.consumption_price_base, usage_points.consumption_price_hc, usage_points.consumption_price_hp, usage_points.production_price, usage_points.offpeak_hours_0, usage_points.offpeak_hours_1, usage_points.offpeak_hours_2, usage_points.offpeak_hours_3, usage_points.offpeak_hours_4, usage_points.offpeak_hours_5, usage_points.offpeak_hours_6, usage_points."plan", usage_points.refresh_addresse, usage_points.refresh_contract, usage_points.token, usage_points.progress, usage_points.progress_status, usage_points.enable, usage_points.consentement_expiration, usage_points.call_number, usage_points.quota_reached, usage_points.quota_limit, usage_points.quota_reset_at, usage_points.last_call, usage_points.ban, usage_points.consumption_max_date, usage_points.consumption_detail_max_date, usage_points.production_max_date, usage_points.production_detail_max_date 
FROM usage_points 
WHERE usage_points.usage_point_id = ?]
[parameters: (19362083904561,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[12:12:33] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by buchnoun** [comment]
> C'est ton cache qui est corrumpu, supprime le cache.db et relance l'intégration. A moins que tu veuille garder l'historique dans le cache.
> 
> Si tu désire garder le cache, je vais mettre une procédure de migration dans le readme.

j'ai viré le fichier enedisgateway.db et j'obtiens toujours la même erreur...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: usage_points.consentement_expiration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/main.py", line 46, in <module>
    DB.set_usage_point(usage_point_id, data)
  File "/app/models/database.py", line 205, in set_usage_point
    usage_points = self.session.scalars(query).one_or_none()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: usage_points.consentement_expiration
[SQL: SELECT usage_points.usage_point_id, usage_points.name, usage_points.cache, usage_points.consumption, usage_points.consumption_detail, usage_points.production, usage_points.production_detail, usage_points.consumption_price_base, usage_points.consumption_price_hc, usage_points.consumption_price_hp, usage_points.production_price, usage_points.offpeak_hours_0, usage_points.offpeak_hours_1, usage_points.offpeak_hours_2, usage_points.offpeak_hours_3, usage_points.offpeak_hours_4, usage_points.offpeak_hours_5, usage_points.offpeak_hours_6, usage_points."plan", usage_points.refresh_addresse, usage_points.refresh_contract, usage_points.token, usage_points.progress, usage_points.progress_status, usage_points.enable, usage_points.consentement_expiration, usage_points.call_number, usage_points.quota_reached, usage_points.quota_limit, usage_points.quota_reset_at, usage_points.last_call, usage_points.ban, usage_points.consumption_max_date, usage_points.consumption_detail_max_date, usage_points.production_max_date, usage_points.production_detail_max_date 
FROM usage_points 
WHERE usage_points.usage_point_id = ?]
[parameters: (19362083904561,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[15:15:49] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by m4dm4rtig4n** [comment]
enedisgateway.db c'est l'ancien fichier de cache.
En 0.8.7 c'est cache.db

**Comment by buchnoun** [comment]
Et il se trouve où car il n’est pas dans mon répertoire config/enedisgateway2mqtt/ ?

**Comment by m4dm4rtig4n** [comment]
Tu est sur HAOS ?

**Comment by buchnoun** [comment]
Oui dernière version

**Comment by buchnoun** [comment]
Tres bien j’essaye ca merci :)

**Comment by buchnoun** [comment]
C'est bon l'application est lancée plus de crash merci :)
En revanche j'ai toujours cet affichage sur ma carte home assistant :
<img width="507" alt="Screenshot 2022-12-07 at 16 22 04" src="https://user-images.githubusercontent.com/37907359/206219221-9da6aa5d-1e98-420c-90ea-38e5012045e4.png">

Est-ce que c'est normal a ce stade ? ou bien c'est un problème lié à la carte ?

**Comment by m4dm4rtig4n** [comment]
Tu as pensé à changer le sensor de la card ?
Maintenant c'est sensor.myelectricaldata_XXXXXXXXXXXXX

**Comment by buchnoun** [comment]
Effectivement je n’avais pas pensé à ca :) Merci une nouvelle fois.
En regardant mon log après reboot j’ai vu que l’appli essaie de récupérer des données qui n’existe pas (j’ai emménagé en août et donc pas de données antérieures)
Est-ce que je peux demander à ne pas tenter la récupération (pour éviter des accès inutiles à l’API d’enedis) ?

2022-12-07 16:09:13.104 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-07 16:09:13.105 -     INFO :  Récupération des données : 2022-08-02 => 2022-08-09
2022-12-07 16:09:13.116 -     INFO :   => Chargement des données depuis MyElectricalData 2022-08-02 => 2022-08-09
2022-12-07 16:09:14.284 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-07 16:09:14.284 -    ERROR : 
2022-12-07 16:09:14.285 -    ERROR :  Echec de la récupération des données.
2022-12-07 16:09:14.285 -    ERROR :   => no measure found for this usage point
2022-12-07 16:09:14.286 -    ERROR :   => 2022-07-26 -> 2022-08-02
2022-12-07 16:09:14.286 -    ERROR : 
2022-12-07 16:09:14.286 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-07 16:09:14.287 -     INFO :  Récupération des données : 2022-07-26 => 2022-08-02
2022-12-07 16:09:14.298 -     INFO :   => Chargement des données depuis MyElectricalData 2022-07-26 => 2022-08-02
2022-12-07 16:09:15.369 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-07 16:09:15.369 -    ERROR : 
2022-12-07 16:09:15.370 -    ERROR :  Echec de la récupération des données.
2022-12-07 16:09:15.371 -    ERROR :   => The requested period cannot be anterior to the meter's last activation date
2022-12-07 16:09:15.371 -    ERROR :   => 2022-07-19 -> 2022-07-26
2022-12-07 16:09:15.372 -    ERROR : 
2022-12-07 16:09:15.372 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-07 16:09:15.373 -  WARNING :  Arrêt de la récupération des données suite à une erreur.
2022-12-07 16:09:15.373 -  WARNING :  Prochain lancement à 2022-12-07 20:09:15.373459
2022-12-07 16:09:15.376 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-07 16:09:15.377 -     INFO :  [19362083904561] STATUS DU COMPTE.
2022-12-07 16:09:15.377 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-07 16:09:15.394 -     INFO :   => Finish
2022-12-07 16:09:15.396 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-07 16:09:15.397 -     INFO :  [19362083904561] EXPORTATION DE DONNÉES DANS MQTT.
2022-12-07 16:09:15.397 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-07 16:09:15.398 -     INFO :  Génération des messages du contrat
2022-12-07 16:09:15.422 -     INFO :   => Finish
2022-12-07 16:09:15.423 -     INFO :  [19362083904561] Génération des messages d'addresse
2022-12-07 16:09:15.459 -     INFO :   => Finish
2022-12-07 16:09:15.460 -     INFO :  Génération des données annuelles
2022-12-07 16:09:15.504 -     INFO :   2022-01-01 => 2022-12-05
2022-12-07 16:09:15.565 -     INFO :   2022-07-15 => 2021-12-31
2022-12-07 16:09:15.595 -     INFO :   => Finish
2022-12-07 16:09:15.597 -     INFO :  Génération des données linéaires
2022-12-07 16:09:15.632 -     INFO :   2021-12-05 => 2022-12-05
2022-12-07 16:09:15.704 -     INFO :   2022-07-15 => 2021-12-05
2022-12-07 16:09:15.735 -     INFO :   => Finish
2022-12-07 16:09:15.736 -     INFO :  Génération des données annuelles détaillées
2022-12-07 16:09:16.277 -     INFO :   2022-01-01 => 2022-12-05
2022-12-07 16:09:17.030 -     INFO :   2022-09-22 => 2021-12-31
2022-12-07 16:09:17.073 -     INFO :   => Finish
2022-12-07 16:09:17.073 -     INFO :  Génération des données linéaires détaillées
2022-12-07 16:09:17.501 -     INFO :   2021-12-05 => 2022-12-05
2022-12-07 16:09:18.235 -     INFO :   2022-09-22 => 2021-12-05
2022-12-07 16:09:18.287 -     INFO :   => Finish
2022-12-07 16:09:18.297 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-07 16:09:18.297 -     INFO :  [19362083904561] EXPORTATION DES DONNÉES DANS HOME ASSISTANT (VIA MQTT)
2022-12-07 16:09:18.297 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-07 16:09:18.363 -     INFO :  current_week
2022-12-07 16:09:18.373 -     INFO :   => 762062
2022-12-07 16:09:18.373 -     INFO :  last_week
2022-12-07 16:09:18.384 -     INFO :   => 787973
2022-12-07 16:09:18.384 -     INFO :  current_week_last_year
2022-12-07 16:09:18.395 -     INFO :   => 0
2022-12-07 16:09:18.396 -     INFO :  last_month
2022-12-07 16:09:18.407 -     INFO :   => 2826681
2022-12-07 16:09:18.408 -     INFO :  current_month
2022-12-07 16:09:18.418 -     INFO :   => 630901
2022-12-07 16:09:18.418 -     INFO :  current_month_last_year
2022-12-07 16:09:18.428 -     INFO :   => 0
2022-12-07 16:09:18.429 -     INFO :  last_month_last_year
2022-12-07 16:09:18.438 -     INFO :   => 0
2022-12-07 16:09:18.439 -     INFO :  current_year
2022-12-07 16:09:18.459 -     INFO :   => 9839365
2022-12-07 16:09:18.460 -     INFO :  current_year_last_year
2022-12-07 16:09:18.470 -     INFO :   => 0
2022-12-07 16:09:18.471 -     INFO :  last_year
2022-12-07 16:09:18.481 -     INFO :   => 0
2022-12-07 16:09:18.481 -     INFO :  yesterday_hp / yesterday_hc
2022-12-07 16:09:18.494 -     INFO :   => HC : 0
2022-12-07 16:09:18.494 -     INFO :   => HP : 0
2022-12-07 16:09:18.495 -     INFO :  peak_offpeak_percent_hp VS peak_offpeak_percent_hc
2022-12-07 16:09:18.755 -     INFO :   => 72.22757155835018
2022-12-07 16:09:18.756 -     INFO :  current_week_evolution
2022-12-07 16:09:18.756 -     INFO :   => -3.2883106400853848
2022-12-07 16:09:18.757 -     INFO :  current_month_evolution
2022-12-07 16:09:18.757 -     INFO :   => 0
2022-12-07 16:09:18.757 -     INFO :  yesterday_evolution
2022-12-07 16:09:18.757 -     INFO :  yesterday
2022-12-07 16:09:18.769 -     INFO :   => 0
2022-12-07 16:09:18.770 -     INFO :  yesterday_1
2022-12-07 16:09:18.781 -     INFO :   => 131997
2022-12-07 16:09:18.781 -     INFO :   => -100.0
2022-12-07 16:09:18.782 -     INFO :  monthly_evolution
2022-12-07 16:09:18.782 -     INFO :  last_month
2022-12-07 16:09:18.793 -     INFO :   => 5653362
2022-12-07 16:09:18.794 -     INFO :  last_month_last_year
2022-12-07 16:09:18.804 -     INFO :   => 0
2022-12-07 16:09:18.805 -     INFO :   => 0
2022-12-07 16:09:19.773 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-07 16:09:19.774 -     INFO : ▌│█║▌║▌║       ___                                 _     _____  _         _       _      _  _  _       ║▌║▌║█│▌
2022-12-07 16:09:19.775 -     INFO : ▌│█║▌║▌║      |_ _| _ __ ___   _ __    ___   _ __ | |_  |  ___|(_) _ __  (_) ___ | |__  | || || |      ║▌║▌║█│▌
2022-12-07 16:09:19.775 -     INFO : ▌│█║▌║▌║       | | | '_ ` _ \ | '_ \  / _ \ | '__|| __| | |_   | || '_ \ | |/ __|| '_ \ | || || |      ║▌║▌║█│▌
2022-12-07 16:09:19.776 -     INFO : ▌│█║▌║▌║       | | | | | | | || |_) || (_) || |   | |_  |  _|  | || | | || |\__ \| | | ||_||_||_|      ║▌║▌║█│▌
2022-12-07 16:09:19.776 -     INFO : ▌│█║▌║▌║      |___||_| |_| |_|| .__/  \___/ |_|    \__| |_|    |_||_| |_||_||___/|_| |_|(_)(_)(_)      ║▌║▌║█│▌
2022-12-07 16:09:19.777 -     INFO : ▌│█║▌║▌║                      |_|                                                                      ║▌║▌║█│▌
2022-12-07 16:09:19.777 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Comment by buchnoun** [comment]
c'est curieux j'ai bien précisé dans config.yaml 
consumption_max_date: "2022-09-01"
consumption_detail_max_date: "2022-09-01"
et 
production: 'false'
dois-je tout de même changer
production_max_date: "2021-06-01"
production_detail_max_date: "2021-06-01"

(au passage pourquoi dans le fichier de config exemple il y a parfois des true ou 'true' ou "true" 
je ne connais pas bien le yaml mais c'est confusant cette histoire de guillemets :-)

**Comment by m4dm4rtig4n** [comment]
Ta donnée n'était peut être pas encore dispo chez Enedis.
L'heure d'arriver est parfois aléatoire....

Après pour les erreursn il y avait une soucis avec l'addon d'HassIO qui vient d'etre fix par le propriaitre de l'addons.
