### ISSUE TITLE
[BUG] - 088 vers 088 : migration ne marche pas

### ISSUE THREAD

**Issue by vingerha** [m4dm4rtig4n/myelectricaldata#192]
Car 088 à évolué j'ai fait un maj de l'image
La migration proposé (renommer cahce>enedisgateway) donne une erreur

EDIT: j'ai abandonnée l'idée de migrer et recommencé la recup de 0 .. :) ... si tu veux...mettre ce ticket "closed"
```
2022-12-08 06:36:02.994 -  WARNING : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ▲ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-08 06:36:02.995 -  WARNING :  MIGRATION DE L'ANCIENNE BASE DE DONNÉES VERS LA NOUVELLE STRUCTURE.
2022-12-08 06:36:02.995 -  WARNING : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ▲ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-08 06:36:02.996 -  WARNING :  Migration des "consumption_daily"
Traceback (most recent call last):
  File "/app/main.py", line 9, in <module>
    from models.ajax import Ajax
  File "/app/models/ajax.py", line 3, in <module>
    from models.jobs import Job
  File "/app/models/jobs.py", line 6, in <module>
    from models.database import Database
  File "/app/models/database.py", line 1139, in <module>
    Database().init_database()
  File "/app/models/database.py", line 41, in __init__
    self.migratev7tov8()
  File "/app/models/database.py", line 60, in migratev7tov8
    date = datetime.strptime(daily[1], "%Y-%m-%d")
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '25960347298299' does not match format '%Y-%m-%d'

**Comment by vingerha** [comment]
Closed as not really important and a full rebuild of cache.db was OK for me
