### ISSUE TITLE
[BUG] - Influxdb HTTP request returns page not found on 0.8.8 

### ISSUE THREAD

**Issue by totoantibes** [m4dm4rtig4n/myelectricaldata#199]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Tour fonctionne nickel en 0.8.7. j'ai réussi à faire des dashboards sur grafana et sur chonograf.

en pullant la version latest (0.8.8) je recois une erreur suivante au démarrage:
J'ai meme essayé le wipe_influx true

```
2022-12-08 16:30:38.882 -  WARNING :   <!> ATTENTION, le mode d'importation "ASYNCHRONOUS" est très consommateur de ressources système.
Traceback (most recent call last):
  File "/app/main.py", line 81, in <module>
    INFLUXDB = InfluxDB(
  File "/app/models/influxdb.py", line 63, in __init__
    self.connect()
  File "/app/models/influxdb.py", line 117, in connect
    self.get_list_retention_policies()
  File "/app/models/influxdb.py", line 137, in get_list_retention_policies
    buckets = self.buckets_api.find_buckets().buckets
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/bucket_api.py", line 119, in find_buckets
    return self._buckets_service.get_buckets(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/buckets_service.py", line 548, in get_buckets
    (data) = self.get_buckets_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/buckets_service.py", line 575, in get_buckets_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 365, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 268, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.10', 'Date': 'Thu, 08 Dec 2022 15:30:38 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found


```
**Configuration**
```
influxdb:
  enable: true
  hostname: 192.168.1.63
  port: 8086
  token: not shown
  org: "-"
  bucket: "myelectricaldata"
  method: asynchronous
(j'ai essayé avec synchronous et aussi ancien format asynchronous: true et false
myelectricaldata:
  "xxxxxxxxxxx":              # Replace XXXXXXXXXXXXXX by your PDL Number. MANDATORY
    enable: 'true'
    name: "Fontanges"
    plan: BASE                 # BASE or HP/HC
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
#    consumption_price_hc: '0'
#    consumption_price_hp: '0'
    consumption_price_base: '0.1740'
    production_max_date: "2020-06-01"
    production_detail_max_date: "2020-06-01"
    production: 'false'
    production_detail: 'false'
#    offpeak_hours: ""         # USE ONLY IF YOU WANT OVERLOAD DEFAULT VALUE, Format : 22h36-06h00;11h30-14h30
    addresses: 'true'
    refresh_addresse: 'false'
    refresh_contract: 'false'

```

**Type d'installation**
Docker, HassIO ?
docker-compose sur rpi3b+

**Version : X.X.X**
influx 1.8.10

**Comment by MrBLJ** [comment]
J'ai exactement la même chose. Je suis passé en 0.8.8-dev aujourd'hui.

**Comment by evenisse** [comment]
cf #203

**Comment by m4dm4rtig4n** [comment]
Fix dans la 0.8.10
