### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by Cissoubaka** [m4dm4rtig4n/myelectricaldata#202]
**Description du bug**
influxdb est desactivé
certainement un soucis de requete sql voir le log d'erreur plus bas

**Configuration**
myelectricaldata:
  "PDL":
    enable: 'true'
    token: *******
    name: "*******"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.16550'
    consumption_price_hc: '0.13723'
    consumption_price_hp: '0.18826'
    consumption_max_date: "2021-04-01"
    consumption_detail_max_date: "2021-04-01"
    #offpeak_hours_0: 22H00-6H00               # LUNDI
    #offpeak_hours_1: 22H00-6H00               # MARDI
    #offpeak_hours_2: 22H00-6H00               # MERCREDI
    #offpeak_hours_3: 22H00-6H00               # JEUDI
    #offpeak_hours_4: 22H00-6H00               # VENDREDI
    #offpeak_hours_5: 22H00-6H00;12H00-14H00   # SAMEDI
    #offpeak_hours_6: 22H00-6H00;12H00-14H00   # DIMANCHE
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    production_max_date: "2021-04-01"
    production_detail_max_date: "2021-04-01"
    refresh_addresse: 'false'
    refresh_contract: 'false'

**Type d'installation**
Docker sur pi3
commande : 
docker run -d -it --restart=unless-stopped --name myelec -v $(pwd):/data -p 5000:5000 -e TZ="Europe/Paris" m4dm4rtig4n/myelectricaldata:latest

**Version : 0.8.8**

log : 
2022-12-09 09:50:43.404 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-09 09:50:43.405 -     INFO :  [***PDL***] RÉCUPÉRATION DE LA CONSOMMATION JOURNALIÈRE :
2022-12-09 09:50:43.406 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-09 09:50:43.465 -     INFO :  Récupération des données : 2022-11-03 => 2022-12-09
2022-12-09 09:50:43.816 -     INFO :   => Chargement des données depuis MyElectricalData 2022-11-03 => 2022-12-09
2022-12-09 09:50:46.650 -    ERROR : (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) datatype mismatch
[SQL: INSERT INTO consumption_daily (id, usage_point_id, date, value, blacklist, fail_count) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('********', '***PDL***', '2022-11-03 00:00:00.000000', '22160', 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: datatype mismatch

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/models/query_daily.py", line 74, in run
    self.db.insert_daily(
  File "/app/models/database.py", line 794, in insert_daily
    daily = self.session.scalars(query).one_or_none()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1660, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2257, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2246, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3526, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) datatype mismatch
[SQL: INSERT INTO consumption_daily (id, usage_point_id, date, value, blacklist, fail_count) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('********', '***PDL***', '2022-11-03 00:00:00.000000', '22160', 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-09 09:50:46.690 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-09 09:50:46.691 -    ERROR : 
2022-12-09 09:50:46.691 -    ERROR :  (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) datatype mismatch
[SQL: INSERT INTO consumption_daily (id, usage_point_id, date, value, blacklist, fail_count) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('********', '***PDL***', '2022-11-03 00:00:00.000000', '22160', 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-09 09:50:46.692 -    ERROR : 
2022-12-09 09:50:46.692 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
Traceback (most recent call last):
  File "/app/models/jobs.py", line 80, in job_import_data
    self.get_consumption()
  File "/app/models/jobs.py", line 252, in get_consumption
    result = Daily(
  File "/app/models/query_daily.py", line 138, in get
    app.LOG.error(error)
UnboundLocalError: local variable 'error' referenced before assignment
2022-12-09 09:50:46.696 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-09 09:50:46.697 -    ERROR : 
2022-12-09 09:50:46.697 -    ERROR :  Erreur lors de la récupération de votre consommation journalière
2022-12-09 09:50:46.698 -    ERROR :  local variable 'error' referenced before assignment
2022-12-09 09:50:46.698 -    ERROR : 
2022-12-09 09:50:46.699 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-09 09:50:46.699 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-09 09:50:46.700 -     INFO :  [***PDL***] RÉCUPÉRATION DE LA CONSOMMATION DÉTAILLÉE :
2022-12-09 09:50:46.700 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-09 09:50:46.736 -     INFO :  Récupération des données : 2022-12-02 => 2022-12-09
2022-12-09 09:50:46.753 -     INFO :   - 11519m absente du relevé.
2022-12-09 09:50:46.753 -     INFO :   => Chargement des données depuis MyElectricalData 2022-12-02 => 2022-12-09
2022-12-09 09:50:48.125 -    ERROR : (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) datatype mismatch
[SQL: INSERT INTO consumption_detail (id, usage_point_id, date, value, interval, measure_type, blacklist, fail_count) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('********', '***PDL***', '2022-12-02 00:00:00.000000', '274', '30', 'HP', 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: datatype mismatch

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/models/query_detail.py", line 115, in run
    self.db.insert_detail(
  File "/app/models/database.py", line 1001, in insert_detail
    detail = self.get_detail_date(usage_point_id, date, mesure_type)
  File "/app/models/database.py", line 899, in get_detail_date
    return self.session.scalars(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1660, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2257, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2246, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3526, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) datatype mismatch
[SQL: INSERT INTO consumption_detail (id, usage_point_id, date, value, interval, measure_type, blacklist, fail_count) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('********', '***PDL***', '2022-12-02 00:00:00.000000', '274', '30', 'HP', 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-09 09:50:48.131 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-09 09:50:48.132 -    ERROR : 
2022-12-09 09:50:48.132 -    ERROR :  (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) datatype mismatch
[SQL: INSERT INTO consumption_detail (id, usage_point_id, date, value, interval, measure_type, blacklist, fail_count) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('********', '***PDL***', '2022-12-02 00:00:00.000000', '274', '30', 'HP', 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-09 09:50:48.133 -    ERROR : 
2022-12-09 09:50:48.133 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
Traceback (most recent call last):
  File "/app/models/jobs.py", line 86, in job_import_data
    self.get_consumption_detail()
  File "/app/models/jobs.py", line 262, in get_consumption_detail
    result = Detail(
  File "/app/models/query_detail.py", line 179, in get
    app.LOG.error(error)
UnboundLocalError: local variable 'error' referenced before assignment
2022-12-09 09:50:48.135 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-09 09:50:48.136 -    ERROR : 
2022-12-09 09:50:48.136 -    ERROR :  Erreur lors de la récupération de votre consommation détaillée
2022-12-09 09:50:48.137 -    ERROR :  local variable 'error' referenced before assignment
2022-12-09 09:50:48.138 -    ERROR : 
2022-12-09 09:50:48.138 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-09 09:50:48.139 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-09 09:50:48.139 -     INFO :  [***PDL***] STATUS DU COMPTE.
2022-12-09 09:50:48.140 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-09 09:50:48.172 -     INFO :   => Finish
2022-12-09 09:50:48.172 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-09 09:50:48.173 -     INFO :  [***PDL***] EXPORTATION DE DONNÉES DANS MQTT.
2022-12-09 09:50:48.173 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-09 09:50:48.174 -     INFO :  Génération des messages du contrat
2022-12-09 09:50:48.203 -     INFO :   => Finish
2022-12-09 09:50:48.204 -     INFO :  [25868596172350] Génération des messages d'addresse
2022-12-09 09:50:48.222 -     INFO :   => Finish
2022-12-09 09:50:48.223 -     INFO :  Génération des données annuelles
2022-12-09 09:50:48.249 -     INFO :   => No data
2022-12-09 09:50:48.250 -     INFO :  Génération des données linéaires
2022-12-09 09:50:48.274 -     INFO :   => No data
2022-12-09 09:50:48.275 -     INFO :  Génération des données annuelles détaillées
2022-12-09 09:50:48.301 -     INFO :   => No data
2022-12-09 09:50:48.302 -     INFO :  Génération des données linéaires détaillées
2022-12-09 09:50:48.328 -     INFO :   => No data
2022-12-09 09:50:48.344 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-09 09:50:48.344 -     INFO :  [***PDL***] EXPORTATION DES DONNÉES DANS HOME ASSISTANT (VIA MQTT)
2022-12-09 09:50:48.345 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-09 09:50:48.412 -     INFO :  current_week
2022-12-09 09:50:48.429 -     INFO :   => 0
2022-12-09 09:50:48.430 -     INFO :  last_week
2022-12-09 09:50:48.447 -     INFO :   => 0
2022-12-09 09:50:48.448 -     INFO :  current_week_last_year
2022-12-09 09:50:48.465 -     INFO :   => 0
2022-12-09 09:50:48.466 -     INFO :  last_month
2022-12-09 09:50:48.483 -     INFO :   => 0
2022-12-09 09:50:48.484 -     INFO :  current_month
2022-12-09 09:50:48.501 -     INFO :   => 0
2022-12-09 09:50:48.502 -     INFO :  current_month_last_year
2022-12-09 09:50:48.519 -     INFO :   => 0
2022-12-09 09:50:48.520 -     INFO :  last_month_last_year
2022-12-09 09:50:48.537 -     INFO :   => 0
2022-12-09 09:50:48.538 -     INFO :  current_year
2022-12-09 09:50:48.555 -     INFO :   => 0
2022-12-09 09:50:48.556 -     INFO :  current_year_last_year
2022-12-09 09:50:48.573 -     INFO :   => 0
2022-12-09 09:50:48.574 -     INFO :  last_year
2022-12-09 09:50:48.591 -     INFO :   => 0
2022-12-09 09:50:48.592 -     INFO :  yesterday_hp / yesterday_hc
2022-12-09 09:50:48.611 -     INFO :   => HC : 0
2022-12-09 09:50:48.612 -     INFO :   => HP : 0
2022-12-09 09:50:48.612 -     INFO :  peak_offpeak_percent_hp VS peak_offpeak_percent_hc
2022-12-09 09:50:48.631 -     INFO :   => 0
2022-12-09 09:50:48.631 -     INFO :  current_week_evolution
2022-12-09 09:50:48.631 -     INFO :   => 0
2022-12-09 09:50:48.632 -     INFO :  current_month_evolution
2022-12-09 09:50:48.632 -     INFO :   => 0
2022-12-09 09:50:48.633 -     INFO :  yesterday_evolution
2022-12-09 09:50:48.633 -     INFO :  yesterday
2022-12-09 09:50:48.651 -     INFO :   => 0
2022-12-09 09:50:48.651 -     INFO :  yesterday_1
2022-12-09 09:50:48.668 -     INFO :   => 0
2022-12-09 09:50:48.669 -     INFO :   => 0
2022-12-09 09:50:48.669 -     INFO :  monthly_evolution
2022-12-09 09:50:48.670 -     INFO :  last_month
2022-12-09 09:50:48.687 -     INFO :   => 0
2022-12-09 09:50:48.688 -     INFO :  last_month_last_year
2022-12-09 09:50:48.706 -     INFO :   => 0
2022-12-09 09:50:48.707 -     INFO :   => 0
2022-12-09 09:50:49.980 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-09 09:50:49.982 -     INFO : ▌│█║▌║▌║       ___                                 _     _____  _         _       _      _  _  _       ║▌║▌║█│▌
2022-12-09 09:50:49.983 -     INFO : ▌│█║▌║▌║      |_ _| _ __ ___   _ __    ___   _ __ | |_  |  ___|(_) _ __  (_) ___ | |__  | || || |      ║▌║▌║█│▌
2022-12-09 09:50:49.984 -     INFO : ▌│█║▌║▌║       | | | '_ ` _ \ | '_ \  / _ \ | '__|| __| | |_   | || '_ \ | |/ __|| '_ \ | || || |      ║▌║▌║█│▌
2022-12-09 09:50:49.985 -     INFO : ▌│█║▌║▌║       | | | | | | | || |_) || (_) || |   | |_  |  _|  | || | | || |\__ \| | | ||_||_||_|      ║▌║▌║█│▌
2022-12-09 09:50:49.985 -     INFO : ▌│█║▌║▌║      |___||_| |_| |_|| .__/  \___/ |_|    \__| |_|    |_||_| |_||_||___/|_| |_|(_)(_)(_)      ║▌║▌║█│▌
2022-12-09 09:50:49.987 -     INFO : ▌│█║▌║▌║                      |_|                                                                      ║▌║▌║█│▌
2022-12-09 09:50:49.988 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Comment by m4dm4rtig4n** [comment]
Ton cache.db est probablement corrompu.
=> https://github.com/m4dm4rtig4n/myelectricaldata#si-vous-rencontrez-des-erreurs-sql-au-d%C3%A9marrage-

**Comment by Cissoubaka** [comment]
oui, vu sur le discord, j'utilise l'addon d'alexbelgium et le cache.db est a l'intérieur du docker.
