### ISSUE TITLE
[HELP] - Erreur au lancement depuis la maj 0.8.8

### ISSUE THREAD

**Issue by YNK22** [m4dm4rtig4n/myelectricaldata#203]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description de la fonctionnalité**

Depuis la maj 0.8.8 j'ai ce message d'erreur :

`━━━━━━━━━━━━━━━━━━
2022-12-10 03:57:06.509 -     INFO :  Display configuration :
2022-12-10 03:57:06.509 -     INFO :    cycle: 14400
2022-12-10 03:57:06.509 -     INFO :    debug: True
2022-12-10 03:57:06.509 -     INFO :    wipe_influxdb:  false
2022-12-10 03:57:06.509 -     INFO :    home_assistant:
2022-12-10 03:57:06.510 -     INFO :      discovery_prefix: homeassistant
2022-12-10 03:57:06.510 -     INFO :      discovery: True
2022-12-10 03:57:06.510 -     INFO :    influxdb:
2022-12-10 03:57:06.510 -     INFO :      method: synchronous
2022-12-10 03:57:06.510 -     INFO :      hostname: a0d7b954-influxdb
2022-12-10 03:57:06.510 -     INFO :      port: 8086
2022-12-10 03:57:06.511 -     INFO :      token: ** hidden **
2022-12-10 03:57:06.511 -     INFO :      org: -
2022-12-10 03:57:06.511 -     INFO :      bucket: enedis/autogen
2022-12-10 03:57:06.511 -     INFO :      enable: True
2022-12-10 03:57:06.511 -     INFO :    mqtt:
2022-12-10 03:57:06.511 -     INFO :      enable: True
2022-12-10 03:57:06.512 -     INFO :      client_id: myelectricaldata
2022-12-10 03:57:06.512 -     INFO :      hostname: core-mosquitto
2022-12-10 03:57:06.512 -     INFO :      port: 1883
2022-12-10 03:57:06.512 -     INFO :      username: ***
2022-12-10 03:57:06.512 -     INFO :      password: ** hidden **
2022-12-10 03:57:06.512 -     INFO :      prefix: myelectricaldata
2022-12-10 03:57:06.513 -     INFO :      qos: 0
2022-12-10 03:57:06.513 -     INFO :      retain: True
2022-12-10 03:57:06.513 -     INFO :    myelectricaldata:
2022-12-10 03:57:06.513 -     INFO :      
*Pdl*:
2022-12-10 03:57:06.513 -     INFO :        
cache: False
2022-12-10 03:57:06.513 -     INFO :        
name: Maison
2022-12-10 03:57:06.514 -     INFO :        consumption: True
2022-12-10 03:57:06.514 -     INFO :        consumption_detail: True
2022-12-10 03:57:06.514 -     INFO :        consumption_detail_max_date: 2021-09-17
2022-12-10 03:57:06.514 -     INFO :        consumption_max_date: 2021-09-17
2022-12-10 03:57:06.514 -     INFO :        consumption_price_base: 0
2022-12-10 03:57:06.514 -     INFO :        consumption_price_hc: 0,13
2022-12-10 03:57:06.514 -     INFO :        consumption_price_hp: 0,17
2022-12-10 03:57:06.515 -     INFO :        enable: true
2022-12-10 03:57:06.515 -     INFO :        refresh_contract: false
2022-12-10 03:57:06.515 -     INFO :        refresh_addresse: false
2022-12-10 03:57:06.515 -     INFO :        plan: HC/HP
2022-12-10 03:57:06.515 -     INFO :        production: False
2022-12-10 03:57:06.515 -     INFO :        production_detail: False
2022-12-10 03:57:06.516 -     INFO :        production_detail_max_date: 
2022-12-10 03:57:06.516 -     INFO :        production_max_date: 
2022-12-10 03:57:06.516 -     INFO :        production_price: 0
2022-12-10 03:57:06.516 -     INFO :        token: ** hidden **
2022-12-10 03:57:06.516 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-10 03:57:06.517 -     INFO :  Check config.yaml :
2022-12-10 03:57:06.517 -     INFO :   => Config valid
2022-12-10 03:57:06.531 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-10 03:57:06.531 -     INFO :  LOADING CONFIGURATION...
2022-12-10 03:57:06.531 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-10 03:57:06.532 -     INFO :  *Pdl*
2022-12-10 03:57:06.552 -     INFO :    => Success
2022-12-10 03:57:06.552 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-10 03:57:06.553 -     INFO :  Connect to MQTT broker core-mosquitto:1883
2022-12-10 03:57:06.559 -     INFO :   => Connection success
2022-12-10 03:57:06.559 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-10 03:57:06.559 -     INFO :  Connect to InfluxDB a0d7b954-influxdb:8086
2022-12-10 03:57:06.595 -     INFO :   => Connection success
2022-12-10 03:57:06.595 -     INFO :   => Methode d'importation : SYNCHRONOUS
Traceback (most recent call last):
  File "/app/main.py", line 81, in <module>
    INFLUXDB = InfluxDB(
  File "/app/models/influxdb.py", line 63, in __init__
    self.connect()
  File "/app/models/influxdb.py", line 117, in connect
    self.get_list_retention_policies()
  File "/app/models/influxdb.py", line 137, in get_list_retention_policies
    buckets = self.buckets_api.find_buckets().buckets
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/bucket_api.py", line 119, in find_buckets
    return self._buckets_service.get_buckets(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/buckets_service.py", line 548, in get_buckets
    (data) = self.get_buckets_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/buckets_service.py", line 575, in get_buckets_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 365, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 268, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.10', 'Date': 'Sat, 10 Dec 2022 02:57:06 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
[03:57:06] FATAL: The app has crashed. Are you sure you entered the correct config options?`

**Type d'installation**
HassIO

**Version : 0.8.8**

**Comment by YNK22** [comment]
Merci d'avance et surtout merci pour tout ce que tu apportes avec cet Addon 👌🏼

**Comment by geobar78** [comment]
Idem j'ai tenté réinstall 

2022-12-10 08:16:09.243 -  WARNING :   - 2021-01 => 749.23kW
2022-12-10 08:16:09.519 -  WARNING :   - 2021-02 => 784.17kW
2022-12-10 08:16:09.824 -  WARNING :   - 2021-03 => 667.2kW
2022-12-10 08:16:10.101 -  WARNING :   - 2021-04 => 555.71kW
2022-12-10 08:16:10.685 -  WARNING :   - 2021-05 => 598.13kW
2022-12-10 08:16:11.012 -  WARNING :   - 2021-06 => 541.2kW
2022-12-10 08:16:11.286 -  WARNING :   - 2021-07 => 619.84kW
2022-12-10 08:16:11.605 -  WARNING :   - 2021-08 => 856.38kW
2022-12-10 08:16:11.863 -  WARNING :   - 2021-09 => 560.17kW
2022-12-10 08:16:12.183 -  WARNING :   - 2021-10 => 776.41kW
2022-12-10 08:16:12.508 -  WARNING :   - 2021-11 => 641.42kW
2022-12-10 08:16:12.763 -  WARNING :   - 2021-12 => 639.01kW
2022-12-10 08:16:13.074 -  WARNING :   - 2022-01 => 931.46kW
2022-12-10 08:16:13.523 -  WARNING :   - 2022-02 => 842.87kW
2022-12-10 08:16:13.814 -  WARNING :   - 2022-03 => 636.66kW
2022-12-10 08:16:14.123 -  WARNING :   - 2022-04 => 570.89kW
2022-12-10 08:16:14.426 -  WARNING :   - 2022-05 => 542.36kW
2022-12-10 08:16:14.746 -  WARNING :   - 2022-06 => 559.34kW
2022-12-10 08:16:15.062 -  WARNING :   - 2022-07 => 673.83kW
2022-12-10 08:16:15.378 -  WARNING :   - 2022-08 => 764.17kW
2022-12-10 08:16:15.689 -  WARNING :   - 2022-09 => 818.67kW
2022-12-10 08:16:16.203 -  WARNING :   - 2022-10 => 593.01kW
2022-12-10 08:16:16.547 -  WARNING :   - 2022-11 => 461.35kW
2022-12-10 08:16:18.616 -  WARNING :  Migration des "production_daily"
2022-12-10 08:16:18.623 -  WARNING :  Migration des "production_detail"
2022-12-10 08:16:18.642 -     INFO :  Configure Databases
/app/models/database.py:114: SAWarning: Column 'consumption_daily.id' is marked as a member of the primary key for table 'consumption_daily', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store NULL.
  day = self.session.scalars(query).one_or_none()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: consumption_daily.id
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/main.py", line 9, in <module>
    from models.ajax import Ajax
  File "/app/models/ajax.py", line 3, in <module>
    from models.jobs import Job
  File "/app/models/jobs.py", line 6, in <module>
    from models.database import Database
  File "/app/models/database.py", line 1141, in <module>
    Database().init_database()
  File "/app/models/database.py", line 114, in init_database
    day = self.session.scalars(query).one_or_none()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1660, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2257, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2246, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3526, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) NOT NULL constraint failed: consumption_daily.id
[SQL: INSERT INTO consumption_daily (usage_point_id, date, value, blacklist, fail_count) VALUES (?, ?, ?, ?, ?)]
[parameters: ('25256439806760', '2020-02-04 00:00:00.000000', 0, 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[08:16:21] FATAL: [31mThe app has crashed. Are you sure you entered the correct config options?[0m

**Comment by LGO44** [comment]
> MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.
> 
> **Description de la fonctionnalité**
> 
> Depuis la maj 0.8.8 j'ai ce message d'erreur :
> 
> `━━━━━━━━━━━━━━━━━━ 2022-12-10 03:57:06.509 - INFO : Display configuration : 2022-12-10 03:57:06.509 - INFO : cycle: 14400 2022-12-10 03:57:06.509 - INFO : debug: True 2022-12-10 03:57:06.509 - INFO : wipe_influxdb: false 2022-12-10 03:57:06.509 - INFO : home_assistant: 2022-12-10 03:57:06.510 - INFO : discovery_prefix: homeassistant 2022-12-10 03:57:06.510 - INFO : discovery: True 2022-12-10 03:57:06.510 - INFO : influxdb: 2022-12-10 03:57:06.510 - INFO : method: synchronous 2022-12-10 03:57:06.510 - INFO : hostname: a0d7b954-influxdb 2022-12-10 03:57:06.510 - INFO : port: 8086 2022-12-10 03:57:06.511 - INFO : token: ** hidden ** 2022-12-10 03:57:06.511 - INFO : org: - 2022-12-10 03:57:06.511 - INFO : bucket: enedis/autogen 2022-12-10 03:57:06.511 - INFO : enable: True 2022-12-10 03:57:06.511 - INFO : mqtt: 2022-12-10 03:57:06.511 - INFO : enable: True 2022-12-10 03:57:06.512 - INFO : client_id: myelectricaldata 2022-12-10 03:57:06.512 - INFO : hostname: core-mosquitto 2022-12-10 03:57:06.512 - INFO : port: 1883 2022-12-10 03:57:06.512 - INFO : username: *** 2022-12-10 03:57:06.512 - INFO : password: ** hidden ** 2022-12-10 03:57:06.512 - INFO : prefix: myelectricaldata 2022-12-10 03:57:06.513 - INFO : qos: 0 2022-12-10 03:57:06.513 - INFO : retain: True 2022-12-10 03:57:06.513 - INFO : myelectricaldata: 2022-12-10 03:57:06.513 - INFO : *Pdl*: 2022-12-10 03:57:06.513 - INFO : cache: False 2022-12-10 03:57:06.513 - INFO : name: Maison 2022-12-10 03:57:06.514 - INFO : consumption: True 2022-12-10 03:57:06.514 - INFO : consumption_detail: True 2022-12-10 03:57:06.514 - INFO : consumption_detail_max_date: 2021-09-17 2022-12-10 03:57:06.514 - INFO : consumption_max_date: 2021-09-17 2022-12-10 03:57:06.514 - INFO : consumption_price_base: 0 2022-12-10 03:57:06.514 - INFO : consumption_price_hc: 0,13 2022-12-10 03:57:06.514 - INFO : consumption_price_hp: 0,17 2022-12-10 03:57:06.515 - INFO : enable: true 2022-12-10 03:57:06.515 - INFO : refresh_contract: false 2022-12-10 03:57:06.515 - INFO : refresh_addresse: false 2022-12-10 03:57:06.515 - INFO : plan: HC/HP 2022-12-10 03:57:06.515 - INFO : production: False 2022-12-10 03:57:06.515 - INFO : production_detail: False 2022-12-10 03:57:06.516 - INFO : production_detail_max_date: 2022-12-10 03:57:06.516 - INFO : production_max_date: 2022-12-10 03:57:06.516 - INFO : production_price: 0 2022-12-10 03:57:06.516 - INFO : token: ** hidden ** 2022-12-10 03:57:06.516 - INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2022-12-10 03:57:06.517 - INFO : Check config.yaml : 2022-12-10 03:57:06.517 - INFO : => Config valid 2022-12-10 03:57:06.531 - INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2022-12-10 03:57:06.531 - INFO : LOADING CONFIGURATION... 2022-12-10 03:57:06.531 - INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2022-12-10 03:57:06.532 - INFO : *Pdl* 2022-12-10 03:57:06.552 - INFO : => Success 2022-12-10 03:57:06.552 - INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2022-12-10 03:57:06.553 - INFO : Connect to MQTT broker core-mosquitto:1883 2022-12-10 03:57:06.559 - INFO : => Connection success 2022-12-10 03:57:06.559 - INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2022-12-10 03:57:06.559 - INFO : Connect to InfluxDB a0d7b954-influxdb:8086 2022-12-10 03:57:06.595 - INFO : => Connection success 2022-12-10 03:57:06.595 - INFO : => Methode d'importation : SYNCHRONOUS Traceback (most recent call last): File "/app/main.py", line 81, in <module> INFLUXDB = InfluxDB( File "/app/models/influxdb.py", line 63, in __init__ self.connect() File "/app/models/influxdb.py", line 117, in connect self.get_list_retention_policies() File "/app/models/influxdb.py", line 137, in get_list_retention_policies buckets = self.buckets_api.find_buckets().buckets File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/bucket_api.py", line 119, in find_buckets return self._buckets_service.get_buckets(**kwargs) File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/buckets_service.py", line 548, in get_buckets (data) = self.get_buckets_with_http_info(**kwargs) # noqa: E501 File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/buckets_service.py", line 575, in get_buckets_with_http_info return self.api_client.call_api( File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api return self.__call_api(resource_path, method, File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api response_data = self.request( File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 365, in request return self.rest_client.GET(url, File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 268, in GET return self.request("GET", url, File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request raise ApiException(http_resp=r) influxdb_client.rest.ApiException: (404) Reason: Not Found HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.10', 'Date': 'Sat, 10 Dec 2022 02:57:06 GMT', 'Content-Length': '19'}) HTTP response body: 404 page not found [03:57:06] FATAL: The app has crashed. Are you sure you entered the correct config options?`
> 
> **Type d'installation** HassIO
> 
> **Version : 0.8.8**

bonjour 
même chose pour moi

**Comment by sh4rks** [comment]
Bonjour,

idem pour moi. Rollback lance sur 0.8.7

**Comment by evenisse** [comment]
Quelle est la version d'influxdb? 1.8?

**Comment by geobar78** [comment]
@evenisse pour moi oui

**Comment by sh4rks** [comment]
@evenisse 1.8.10 pour moi aussi. J’utilise l’addon influxdb

**Comment by YNK22** [comment]
> Quelle est la version d'influxdb? 1.8?

Oui

**Comment by geobar78** [comment]
J'ai la même erreur en passant Influxdb à false donc je ne pense pas que le souci vienne de la version d'influx

**Comment by evenisse** [comment]
Une PR a été faite pour corriger la connexion à influxDB 1.8 : https://github.com/m4dm4rtig4n/myelectricaldata/pull/207

**Comment by geobar78** [comment]
@evenisse super merci

**Comment by buddy31130** [comment]
Bonjour, comment faites vous pour voir votre version de influxDB ? Je suis sur HassOS et ma version de influxDB est très différente de la votre. Je suis a la version 4.5.0 avec ces erreurs.

**Comment by geobar78** [comment]
@buddy31130 bonjour, moi aussi j'ai eu du mal ;-) l'addon est nous aussi en 4.5.0 mais cet addon est sur une base Influx 1.8, de ce que j'ai compris quand il y a chronograph et Kapacitor qui viennent avec Influx c'est que tu es sur une version 1.8, si on te parle que de Influx c'est que vraisemblablement tu es en 2.x car chronograph et Kapacitor y sont intégrés, ça va avec tout un tas d'autres évolutions dont j'ai même pas idée ni la compréhension.

**Comment by sh4rks** [comment]
@buddy31130 
C’est écrit dans l’erreur : 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.10',

**Comment by buddy31130** [comment]
@geobar78 & @sh4rks Merci pour les précisions ! Effectivement, j'ai bien chronograph et Kapacitor. Et après vérification, l'erreur dit bien que j'ai la versions 1.8.1 :)
Merci encore :)

**Comment by m4dm4rtig4n** [comment]
Fix dans la 0.8.10

**Comment by YNK22** [comment]
Super merci beaucoup !
