### ISSUE TITLE
[BUG] - Pas de remontée de la consommation de la veille

### ISSUE THREAD

**Issue by TeddyLafrite** [m4dm4rtig4n/myelectricaldata#206]
Idem à #173 et ce sur 2 installations différentes

numPDL: XXX
activationDate: 2020-06-13 00:00:00
lastUpdate: 2022-12-10 09:38:01
timeLastCall: 2022-12-10 09:38:01
yesterdayDate: 2022-12-09
yesterday: 0
yesterdayLastYearDate: 2021-12-10
yesterdayLastYear: 0
daily: 0, 13.8, 12.7, 14.3, 13.3, 21.5, 20.7
current_week: 96.4
last_week: 67.5
day_1: 0
day_2: 13.8
day_3: 12.7
day_4: 14.3
day_5: 13.3
day_6: 21.5
day_7: 20.7
current_week_last_year: 97.9
last_month: 248.3
current_month: 114.1
current_month_last_year: 119.3
last_month_last_year: 349.7
last_year: 3873.7
current_year: 2845.9
current_year_last_year: 3552.1
dailyweek: 2022-12-09, 2022-12-08, 2022-12-07, 2022-12-06, 2022-12-05, 2022-12-04, 2022-12-03
dailyweek_cost: 0, 2, 1.9, 2.1, 2, 3.2, 3
dailyweek_costHP: 0, 0, 0, 0, 0, 0, 0
dailyweek_HP: 0, 13.8, 12.7, 14.3, 13.3, 21.5, 20.7
daily_cost: 0
yesterday_HP_cost: 0
yesterday_HP: 0
day_1_HP: 0
day_2_HP: 13836
day_3_HP: 12696
day_4_HP: 14293
day_5_HP: 13306
day_6_HP: 21527
day_7_HP: 20734
dailyweek_costHC: 0, 0, 0, 0, 0, 0, 0
dailyweek_HC: 0, 0, 0, 0, 0, 0, 0
yesterday_HC_cost: 0
yesterday_HC: 0
day_1_HC: 0
day_2_HC: 0
day_3_HC: 0
day_4_HC: 0
day_5_HC: 0
day_6_HC: 0
day_7_HC: 0
peak_offpeak_percent: 0
monthly_evolution: -28.99
current_week_evolution: 42.7
current_month_evolution: -4.38
yesterday_evolution: -100
friendly_name: myelectricaldata_XXXXX
errorLastCall: 
errorLastCallInterne: 
current_week_number: 49
offpeak_hours_enedis: Lundi ();Mardi ();Mercredi ();Jeudi ();Vendredi ();Samedi ();Dimanche ();
offpeak_hours: 
- - - ''
- - - ''
- - - ''
- - - ''
- - - ''
- - - ''
- - - ''

subscribed_power: 6 kVA
unit_of_measurement: kWh

auto_update: true
installed_version: 0.8.8
in_progress: false
latest_version: 0.8.8
release_summary: 
## 0.8.8 (10-12-2022)
- Update to latest version from m4dm4rtig4n/myelectricaldata

## 0.8.7 (03-12-2022)
- Update to latest version from m4dm4rtig4n/myelectricaldata

## 0.8.8-dev (03-12-2022)
- Update to latest version from m4dm4rtig4n/myelectricaldata
release_url: null
skipped_version: null
title: MyElectricalData
entity_picture: /api/hassio/addons/db21ed7f_enedisgateway2mqtt/icon
friendly_name: MyElectricalData Update
supported_features: 25

**Comment by vingerha** [comment]
erreurs?

**Comment by TeddyLafrite** [comment]
[SQL: INSERT INTO consumption_detail (id, usage_point_id, date, value, interval, measure_type, blacklist, fail_count) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('3XXXXXXXXXX72b00d170ceffb4', '2249XXXXXXXXXXX834', '2022-12-03 00:00:00.000000', '148', '30', 'HP', 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-10 17:09:14.191 -    ERROR : 
2022-12-10 17:09:14.192 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
Traceback (most recent call last):
  File "/app/models/jobs.py", line 86, in job_import_data
    self.get_consumption_detail()
  File "/app/models/jobs.py", line 262, in get_consumption_detail
    result = Detail(
  File "/app/models/query_detail.py", line 179, in get
    app.LOG.error(error)
UnboundLocalError: local variable 'error' referenced before assignment
2022-12-10 17:09:14.192 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-10 17:09:14.193 -    ERROR : 
2022-12-10 17:09:14.193 -    ERROR :  Erreur lors de la récupération de votre consommation détaillée
2022-12-10 17:09:14.193 -    ERROR :  local variable 'error' referenced before assignment


De : Arjan
Envoyé le :samedi 10 décembre 2022 15:12
À : m4dm4rtig4n/myelectricaldata
Cc : TeddyLafrite; Author
Objet :Re: [m4dm4rtig4n/myelectricaldata] [BUG] - Pas de remontée de la consommation de la veille (Issue #206)

erreurs?

**Comment by evenisse** [comment]
Cette erreur sera corrigée avec la PR #209
