### ISSUE TITLE
[BUG] - Addon crash depuis le passage en v0.0.8

### ISSUE THREAD

**Issue by floow77** [m4dm4rtig4n/myelectricaldata#208]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Depuis le passage à la version 0.8.8

`2022-12-10 17:15:59.117 -     INFO :   => Methode d'importation : SYNCHRONOUS
Traceback (most recent call last):
  File "/app/main.py", line 81, in <module>
    INFLUXDB = InfluxDB(
  File "/app/models/influxdb.py", line 63, in __init__
    self.connect()
  File "/app/models/influxdb.py", line 117, in connect
    self.get_list_retention_policies()
  File "/app/models/influxdb.py", line 137, in get_list_retention_policies
    buckets = self.buckets_api.find_buckets().buckets
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/bucket_api.py", line 119, in find_buckets
    return self._buckets_service.get_buckets(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/buckets_service.py", line 548, in get_buckets
    (data) = self.get_buckets_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/buckets_service.py", line 575, in get_buckets_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 365, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 268, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.10', 'Date': 'Sat, 10 Dec 2022 16:15:59 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
[17:15:59] FATAL: The app has crashed. Are you sure you entered the correct config options?`

**Configuration**
`cycle: 14400
debug: true
wipe_influxdb: false
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: true
  hostname: influxdb
  port: 8086
  token: token:token
  org: "-"
  bucket: "homeassistant/autogen" 
  asynchronous: "false"
mqtt:
  enable: true
  hostname: mosquitto
  port: 1883
  username: "login"
  password: "pass"
  prefix: myelectricaldata
  client_id: myelectricaldata # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
myelectricaldata:
  "22149782812345":
    enable: "true"
    token: TOKEN=
    name: "Maison"
    addresses: "true"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_price_base: "0.1679" 
    consumption_price_hc: "0.1422" 
    consumption_price_hp: "0.1769" 
    consumption_max_date: "2021-07-03"
    consumption_detail_max_date: "2021-07-03"
    offpeak_hours_0: 01H36-8H06;12H06-13H36 # LUNDI
    offpeak_hours_1: 01H36-8H06;12H06-13H36 # MARDI
    offpeak_hours_2: 01H36-8H06;12H06-13H36 # MERCREDI
    offpeak_hours_3: 01H36-8H06;12H06-13H36 # JEUDI
    offpeak_hours_4: 01H36-8H06;12H06-13H36 # VENDREDI
    offpeak_hours_5: 01H36-8H06;12H06-13H36 # SAMEDI
    offpeak_hours_6: 01H36-8H06;12H06-13H36 # DIMANCHE
    plan: HC/HP
    production: "false"
    production_detail: "false"
    production_price: "0.0"
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: "false"
    refresh_contract: "false"
`

**Type d'installation**
 HassIO 

**Version : 0.0.8 **

**Comment by gael1980** [comment]
Bonjour,
J'ai la même erreur depuis le passage vers la version 8.
Merci pour votre aide.
Gaël

**Comment by evenisse** [comment]
Duplicate #203 Une PR a été proposée

**Comment by gael1980** [comment]
ça marche, merci.

**Comment by fabien4444** [comment]
Bonjour
j'ai le même type d'erreur sur une fresh installation aujourd'hui (influxDB 3.0)
