### ISSUE TITLE
[BUG] - Exception sur  la récupération du contrat

### ISSUE THREAD

**Issue by evenisse** [m4dm4rtig4n/myelectricaldata#213]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
```2022-12-11 22:18:53.415 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-11 22:18:53.416 -     INFO :  [XXXXXXXXXXXXXX] RÉCUPÉRATION DU CONTRAT :
2022-12-11 22:18:53.416 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-11 22:18:53.436 -     INFO :   => No cache
Traceback (most recent call last):
  File "/app/models/jobs.py", line 68, in job_import_data
    self.get_contract()
  File "/app/models/jobs.py", line 228, in get_contract
    result = Contract(
  File "/app/models/query_contract.py", line 84, in get
    result = self.run()
  File "/app/models/query_contract.py", line 76, in run
    "description": json.loads(query_response.text)["detail"]
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-12-11 22:18:53.573 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-11 22:18:53.573 -    ERROR : 
2022-12-11 22:18:53.573 -    ERROR :  Erreur lors de la récupération des informations du contract
2022-12-11 22:18:53.574 -    ERROR :  Expecting value: line 1 column 1 (char 0)
2022-12-11 22:18:53.574 -    ERROR : 
2022-12-11 22:18:53.574 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Configuration**
```  "XXXXXXXXXXXXXX":
    token: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
    name: "Igny"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.165832'
    consumption_price_hc: '0.147239'
    consumption_price_hp: '0.183801'
    consumption_max_date: '2021-09-07'
    consumption_detail_max_date: '2021-09-07'
    offpeak_hours_0: 1H36-7H36;13H06-15H06    # LUNDI
    offpeak_hours_1: 1H36-7H36;13H06-15H06    # MARDI
    offpeak_hours_2: 1H36-7H36;13H06-15H06    # MERCREDI
    offpeak_hours_3: 1H36-7H36;13H06-15H06    # JEUDI
    offpeak_hours_4: 1H36-7H36;13H06-15H06    # VENDREDI
    offpeak_hours_5: 1H36-7H36;13H06-15H06    # SAMEDI
    offpeak_hours_6: 1H36-7H36;13H06-15H06    # DIMANCHE
    plan: BASE
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    enable: 'true'
```

**Type d'installation**
Docker, HassIO ?

**Version : 0.8.9-beta1**

**Comment by m4dm4rtig4n** [comment]
C'est ton point de livraison & token qui ne sont pas bon et ne remonte pas d'information, je vais améliorer le catching d'erreurs.
