### ISSUE TITLE
[BUG] - JSON parsing error

### ISSUE THREAD

**Issue by evenisse** [m4dm4rtig4n/myelectricaldata#214]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Cette exception semble être pour des données manquantes dans le résultat.
```
2022-12-11 22:24:56.803 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-11 22:24:56.803 -     INFO :  [XXXXXXXXXXXXXX] RÉCUPÉRATION DE LA CONSOMMATION JOURNALIÈRE :
2022-12-11 22:24:56.803 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-11 22:24:57.012 -     INFO :  Récupération des données : 2022-11-05 => 2022-12-11
2022-12-11 22:24:57.167 -     INFO :   => Chargement des données depuis MyElectricalData 2022-11-05 => 2022-12-11
2022-12-11 22:25:02.383 -     INFO :  Récupération des données : 2022-09-30 => 2022-11-05
2022-12-11 22:25:02.553 -     INFO :   => Chargement des données depuis MyElectricalData 2022-09-30 => 2022-11-05
2022-12-11 22:25:06.982 -     INFO :  Récupération des données : 2022-08-25 => 2022-09-30
2022-12-11 22:25:07.253 -     INFO :   => Chargement des données depuis MyElectricalData 2022-08-25 => 2022-09-30
2022-12-11 22:25:11.580 -     INFO :  Récupération des données : 2022-07-20 => 2022-08-25
2022-12-11 22:25:11.752 -     INFO :   => Chargement des données depuis MyElectricalData 2022-07-20 => 2022-08-25
2022-12-11 22:25:13.640 -     INFO :  Récupération des données : 2022-06-14 => 2022-07-20
2022-12-11 22:25:13.820 -     INFO :   => Chargement des données depuis MyElectricalData 2022-06-14 => 2022-07-20
2022-12-11 22:25:15.558 -     INFO :  Récupération des données : 2022-05-09 => 2022-06-14
2022-12-11 22:25:15.745 -     INFO :   => Chargement des données depuis MyElectricalData 2022-05-09 => 2022-06-14
2022-12-11 22:25:17.664 -     INFO :  Récupération des données : 2022-04-03 => 2022-05-09
2022-12-11 22:25:17.859 -     INFO :   => Chargement des données depuis MyElectricalData 2022-04-03 => 2022-05-09
2022-12-11 22:25:19.195 -     INFO :  Récupération des données : 2022-02-26 => 2022-04-03
2022-12-11 22:25:19.429 -     INFO :   => Chargement des données depuis MyElectricalData 2022-02-26 => 2022-04-03
2022-12-11 22:25:20.978 -     INFO :  Récupération des données : 2022-01-21 => 2022-02-26
2022-12-11 22:25:21.162 -     INFO :   => Chargement des données depuis MyElectricalData 2022-01-21 => 2022-02-26
2022-12-11 22:25:22.877 -     INFO :  Récupération des données : 2021-12-16 => 2022-01-21
2022-12-11 22:25:23.045 -     INFO :   => Chargement des données depuis MyElectricalData 2021-12-16 => 2022-01-21
2022-12-11 22:25:23.180 -    ERROR : Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/models/query_daily.py", line 92, in run
    "description": json.loads(data.text)["detail"],
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-12-11 22:25:23.181 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-11 22:25:23.181 -    ERROR : 
2022-12-11 22:25:23.181 -    ERROR :  Expecting value: line 1 column 1 (char 0)
2022-12-11 22:25:23.181 -    ERROR : 
2022-12-11 22:25:23.181 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
Traceback (most recent call last):
  File "/app/models/jobs.py", line 80, in job_import_data
    self.get_consumption()
  File "/app/models/jobs.py", line 252, in get_consumption
    result = Daily(
  File "/app/models/query_daily.py", line 138, in get
    app.LOG.error(error)
UnboundLocalError: local variable 'error' referenced before assignment
2022-12-11 22:25:23.183 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-11 22:25:23.183 -    ERROR : 
2022-12-11 22:25:23.183 -    ERROR :  Erreur lors de la récupération de votre consommation journalière
2022-12-11 22:25:23.183 -    ERROR :  local variable 'error' referenced before assignment
2022-12-11 22:25:23.183 -    ERROR : 
2022-12-11 22:25:23.183 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-11 22:25:23.184 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-11 22:25:23.184 -     INFO :  [XXXXXXXXXXXXXX] RÉCUPÉRATION DE LA CONSOMMATION DÉTAILLÉE :
2022-12-11 22:25:23.184 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-11 22:25:23.197 -     INFO :  Récupération des données : 2022-12-04 => 2022-12-11
2022-12-11 22:25:23.203 -     INFO :   - 11519m absente du relevé.
2022-12-11 22:25:23.203 -     INFO :   => Chargement des données depuis MyElectricalData 2022-12-04 => 2022-12-11
2022-12-11 22:25:28.842 -     INFO :  Récupération des données : 2022-11-27 => 2022-12-04
2022-12-11 22:25:28.862 -     INFO :   - 10079m absente du relevé.
2022-12-11 22:25:28.862 -     INFO :   => Chargement des données depuis MyElectricalData 2022-11-27 => 2022-12-04
2022-12-11 22:25:28.989 -    ERROR : Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/models/query_detail.py", line 136, in run
    "description": json.loads(data.text)["detail"],
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-12-11 22:25:28.990 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-11 22:25:28.991 -    ERROR : 
2022-12-11 22:25:28.991 -    ERROR :  Expecting value: line 1 column 1 (char 0)
2022-12-11 22:25:28.991 -    ERROR : 
2022-12-11 22:25:28.991 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-11 22:25:28.991 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-11 22:25:28.991 -    ERROR : 
2022-12-11 22:25:28.991 -    ERROR :  Echec de la récupération des données.
2022-12-11 22:25:28.991 -    ERROR :   => MyElectricalData est indisponible.
2022-12-11 22:25:28.991 -    ERROR :   => 2022-11-20 -> 2022-11-27
2022-12-11 22:25:28.992 -    ERROR : 
2022-12-11 22:25:28.992 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-11 22:25:28.992 -     INFO :  Récupération des données : 2022-11-20 => 2022-11-27
2022-12-11 22:25:29.006 -     INFO :   - 11519m absente du relevé.
2022-12-11 22:25:29.007 -     INFO :   => Chargement des données depuis MyElectricalData 2022-11-20 => 2022-11-27
2022-12-11 22:25:34.807 -     INFO :  Récupération des données : 2022-11-13 => 2022-11-20
2022-12-11 22:25:34.829 -     INFO :   - 10079m absente du relevé.
2022-12-11 22:25:34.829 -     INFO :   => Chargement des données depuis MyElectricalData 2022-11-13 => 2022-11-20

```

**Configuration**
Il me faut la partie enedis_gateway de votre config.yml, sans les PDL et Token.

**Type d'installation**
Docker, HassIO ?

**Version : 0.8.9-beta1**

**Comment by m4dm4rtig4n** [comment]
Fix avec ma mep de ce midi.
