### ISSUE TITLE
[HELP] - App crash since v8.8 same with v8.10

### ISSUE THREAD

**Issue by geobar78** [m4dm4rtig4n/myelectricaldata#219]
Bonjour, j'ai toujours la même erreur qui se solde par un crash de l'app juste après  Configure Database, depuis l'installation de la version 8.8, la mise à jour n'a pas corrigé mon souci, j'ai tenté une désinstallation réinstallation de l'addon, idem. 

**Description de la fonctionnalité**

2022-12-13 09:19:24.697 -  WARNING :   - 2021-01 => 749.23kW
2022-12-13 09:19:24.945 -  WARNING :   - 2021-02 => 784.17kW
2022-12-13 09:19:25.317 -  WARNING :   - 2021-03 => 667.2kW
2022-12-13 09:19:25.678 -  WARNING :   - 2021-04 => 555.71kW
2022-12-13 09:19:26.392 -  WARNING :   - 2021-05 => 598.13kW
2022-12-13 09:19:26.888 -  WARNING :   - 2021-06 => 541.2kW
2022-12-13 09:19:27.254 -  WARNING :   - 2021-07 => 619.84kW
2022-12-13 09:19:27.633 -  WARNING :   - 2021-08 => 856.38kW
2022-12-13 09:19:27.903 -  WARNING :   - 2021-09 => 560.17kW
2022-12-13 09:19:28.239 -  WARNING :   - 2021-10 => 776.41kW
2022-12-13 09:19:28.598 -  WARNING :   - 2021-11 => 641.42kW
2022-12-13 09:19:28.860 -  WARNING :   - 2021-12 => 639.01kW
2022-12-13 09:19:29.217 -  WARNING :   - 2022-01 => 931.46kW
2022-12-13 09:19:29.710 -  WARNING :   - 2022-02 => 842.87kW
2022-12-13 09:19:30.016 -  WARNING :   - 2022-03 => 636.66kW
2022-12-13 09:19:30.382 -  WARNING :   - 2022-04 => 570.89kW
2022-12-13 09:19:30.756 -  WARNING :   - 2022-05 => 542.36kW
2022-12-13 09:19:31.115 -  WARNING :   - 2022-06 => 559.34kW
2022-12-13 09:19:31.512 -  WARNING :   - 2022-07 => 673.83kW
2022-12-13 09:19:31.930 -  WARNING :   - 2022-08 => 764.17kW
2022-12-13 09:19:32.348 -  WARNING :   - 2022-09 => 818.67kW
2022-12-13 09:19:32.860 -  WARNING :   - 2022-10 => 593.01kW
2022-12-13 09:19:33.245 -  WARNING :   - 2022-11 => 461.35kW
2022-12-13 09:19:35.302 -  WARNING :  Migration des "production_daily"
2022-12-13 09:19:35.833 -  WARNING :  Migration des "production_detail"
2022-12-13 09:19:36.592 -     INFO :  Configure Databases
/app/models/database.py:114: SAWarning: Column 'consumption_daily.id' is marked as a member of the primary key for table 'consumption_daily', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store NULL.
  day = self.session.scalars(query).one_or_none()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: consumption_daily.id
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/main.py", line 9, in <module>
    from models.ajax import Ajax
  File "/app/models/ajax.py", line 3, in <module>
    from models.jobs import Job
  File "/app/models/jobs.py", line 6, in <module>
    from models.database import Database
  File "/app/models/database.py", line 1141, in <module>
    Database().init_database()
  File "/app/models/database.py", line 114, in init_database
    day = self.session.scalars(query).one_or_none()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1660, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2257, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2246, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3526, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) NOT NULL constraint failed: consumption_daily.id
[SQL: INSERT INTO consumption_daily (usage_point_id, date, value, blacklist, fail_count) VALUES (?, ?, ?, ?, ?)]
[parameters: ('25256439806760', '2020-02-04 00:00:00.000000', 0, 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[09:19:43] FATAL: [31mThe app has crashed. Are you sure you entered the correct config options?[0m

**Type d'installation**
HassIO

**Version : 20022.12.4**
Influx v1.8.x

**Comment by geobar78** [comment]
@twolaw tu tiens une piste, de ce que j'ai compris le fichier enedisgateway.db n'est plus utilisé car l'addon crée sa propre db. Mais je ne l'avais pas enlevé pour autant. Quand tu n'as plus le fichier tes importations et tout le reste fonctionne ?

**Comment by twolaw** [comment]
L'intérêt de `enedisgateway.db` est de pouvoir importer (suite au changement de version de l'addon) toutes les données déjà récupérées précédemment.
Là j'ai l'impression qu'on est obligé de se taper toute la récupération de l'historique via la passerelle myElectricalData à cause de ce problème d'import `enedisgateway.db` vers `cache.db`.

D'ailleurs je ne sais pas où est ce fichier `cache.db` ?

**Comment by geobar78** [comment]
@twolaw de ce que j'ai compris il n'est pas accessible, il est crée et géré par ha ou l'addon par un "symlink"

**Comment by geobar78** [comment]
ha oui comme quoi lire jusqu'au bout, je mérite le fouet 

Comment migrer de EnedisGateway2MQTT vers MyElectricalData ?
Pour migrer proprement depuis EnedisGateway2MQTT et avant de lancer la migration vers une version >= 0.8.0, merci de respecter cette procédure :

Arrêter l’integration
Backup le fichier enedisgateway.db (au cas où)
Renommer l’actuel en enedisgateway.db.wait
Migrer en 0.8.X (Attention le fichier de config a changé vous pouvez reprendre l’exemple [ici](https://github.com/m4dm4rtig4n/myelectricaldata/blob/master/config.exemple.yaml))
Démarrer en 0.8.X pour initialiser le nouveau cache.
Arrêter l’intégration.
Renommer le enedisgateway.db.wait en enedisgateway.db
Re-lancer l’intégration, il va migrer les anciennes données du enedisgateway.db vers le cache.db (visible dans les logs)

**Comment by twolaw** [comment]
Il ne précise pas combien de temps il faut attendre pour arrêter l'intégration une fois qu'on a démarré en 0.8.X.
Ou s'il faut attendre un signal bien précis dans les logs...

**Comment by geobar78** [comment]
après je n'avais pas eu le pb de la version 7 la version 8.0, ça n'est apparut que sur la 8.8 (donc de la 8.7 à la 8.8 je suppose) et la 8.10 donc je ne sais pas te dire

**Comment by geobar78** [comment]
bon j'ai tenté de remettre enedisgateway.db quand le log m'a affiché import finish et retour de l'erreur au reboot de l'addon, donc je suppose que mon enedisgateway.db est corrompu. Vu que j'ai pas fait de backup du fichier, dès que j'ai le temps je lancerai un restore de mon système d'il y a 4 jours pour récupérer le fichier et retenterai le coup, ou alors j'attends les 3 ou 4 jours nécessaires pour tout réimporter et avoir une base propre.... je me tâte

**Comment by m4dm4rtig4n** [comment]
Si vous êtes des utilisateur d'HAOS, je vous propose plutot de suivre le sujet sur un post que j'ai crée sur le dépot d'Alexbelgium qui est la personne qui mantient l'addon sur HA.
https://github.com/alexbelgium/hassio-addons/issues/600
