### ISSUE TITLE
[BUG] - influxdb TimeOut

### ISSUE THREAD

**Issue by gael1980** [m4dm4rtig4n/myelectricaldata#226]
Bonjour,

**Description du bug**
J'ai des time out dans l'export vers influx.
Pas de pb pour la console annuelle, mais pb avec la console détail.

022-12-14 11:44:57.677 -     INFO :   - 2021-09
2022-12-14 11:45:07.090 -     INFO :   - 2021-08
2022-12-14 11:45:18.071 -     INFO :   - 2021-07
2022-12-14 11:45:18.708 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-14 11:45:18.709 -     INFO :  [02541244566121] EXPORTATION DES DONNÉES "CONSUMPTION_DETAIL" DANS INFLUXDB
2022-12-14 11:45:18.709 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-14 11:45:19.399 -     INFO :   - 2021-08
2022-12-14 11:46:52.262 -     INFO :   - 2021-10
Traceback (most recent call last):
  File "/app/models/jobs.py", line 182, in job_import_data
    ExportInfluxDB(self.usage_point_id).detail(
  File "/app/models/export_influxdb.py", line 65, in detail
    app.INFLUXDB.write(
  File "/app/models/influxdb.py", line 167, in write
    self.write_api.write(bucket=self.bucket, org=self.org, record=record)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 374, in write
    results = list(map(write_payload, payloads.items()))
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 372, in write_payload
    return self._post_write(_async_req, bucket, org, final_string, payload[0])
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 483, in _post_write
    return self._write_service.post_write(org=org, bucket=bucket, body=body, precision=precision,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 60, in post_write
    (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 90, in post_write_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Request-Id': 'e3d68555-7b9c-11ed-ad12-0242ac1e2106', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Error': 'timeout', 'X-Influxdb-Version': '1.8.10', 'X-Request-Id': 'e3d68555-7b9c-11ed-ad12-0242ac1e2106', 'Date': 'Wed, 14 Dec 2022 10:49:00 GMT', 'Content-Length': '20'})
HTTP response body: {"error":"timeout"}
2022-12-14 11:49:01.800 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-14 11:49:01.801 -    ERROR : 
2022-12-14 11:49:01.801 -    ERROR :  Erreur lors de l'exportation des données dans InfluxDB
2022-12-14 11:49:01.801 -    ERROR :  (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Request-Id': 'e3d68555-7b9c-11ed-ad12-0242ac1e2106', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Error': 'timeout', 'X-Influxdb-Version': '1.8.10', 'X-Request-Id': 'e3d68555-7b9c-11ed-ad12-0242ac1e2106', 'Date': 'Wed, 14 Dec 2022 10:49:00 GMT', 'Content-Length': '20'})
HTTP response body: {"error":"timeout"}
2022-12-14 11:49:01.802 -    ERROR : 
2022-12-14 11:49:01.802 -    ERROR : 

**Configuration**
cycle: 14400
debug: false
home_assistant:
  card_myenedis: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  asynchronous: "false"
  method: synchronous
  bucket: "MyElectrical/autogen"
  enable: true
  hostname: a0d7b954-influxdb
  org: "-"
  port: 8086
  token: xxx:xxx
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: 192.168.0.5
  password: "hass"
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: "hass"
myelectricaldata:
  "xxx":
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: ""
    consumption_max_date: ""
    consumption_price_base: "0.1680"
    consumption_price_hc: "0.1263"
    consumption_price_hp: "0.1678"
    enable: true
    offpeak_hours_0: "2H06-8H06;15H06-17H06"
    offpeak_hours_1: "2H06-8H06;15H06-17H06"
    offpeak_hours_2: "2H06-8H06;15H06-17H06"
    offpeak_hours_3: "2H06-8H06;15H06-17H06"
    offpeak_hours_4: "2H06-8H06;15H06-17H06"
    offpeak_hours_5: "2H06-8H06;15H06-17H06"
    offpeak_hours_6: "2H06-8H06;15H06-17H06"
    plan: HP/HC
    name: "Maison"
    production: false
    production_detail: false
    production_detail_max_date: ""
    production_max_date: ""
    production_price: 0
    token: xxx

**Type d'installation**
Home assistant OS
Influxdb, installation depuis les modules complémentaires de HASS.

**Version : 0.8.10**

**Comment by YNK22** [comment]
Je pense que tu devrais retirer la ligne ci-dessous au niveau de la config du fichier yaml:

`asynchronous: "false"`

**Comment by gael1980** [comment]
OK, Merci.
je vais essayer ce soir.
Merci pour ton aide

**Comment by gael1980** [comment]
On dirait que c'est bon.
Merci
