### ISSUE TITLE
[BUG] - Erreur avec le client pendant un import

### ISSUE THREAD

**Issue by bdbogjoe** [m4dm4rtig4n/myelectricaldata#230]
**Description du bug**
Pendant l'import j'essaie d'accéder au client, mais j'ai cette exception : 
```
2022-12-16 12:18:46.716 -    ERROR : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/main.py", line 146, in main
    return Index().display()
  File "/app/templates/index.py", line 27, in display
    if app.DB.lock_status():
  File "/app/models/database.py", line 156, in lock_status
    if str(self.session.scalars(query).one_or_none()) == "1":
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1706, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 594, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.

```

**Type d'installation**
Docker

**Version : 0.8.10**

**Comment by m4dm4rtig4n** [comment]
Hello, 
Normalement le client est bloquer pendant l'import car la base nosql est lock pendant le traitement.
Mais il arrive que l'ihm reste accèssible si tu lance l'import dans une autre fenetre ou via le job.

C'est un point que je doit améliorer, merci pour la remonté.

**Comment by bdbogjoe** [comment]
la première fois il me semble que j'ai bien la page d'attente, mais ensuite si je fais un refresh j'ai cette erreur.

**Comment by m4dm4rtig4n** [comment]
Je viens d'ajouter un check en plus sur tt les pages pour eviter ce genre de soucis dans la 0.8.11 qui va pop prochainement.

**Comment by m4dm4rtig4n** [comment]
Bon j'ai détecter un souci suite à mon fix sur le 0.8.11-beta2.
Du coup j'ai changer la méthode de lock de la bdd avec un fichier ".lock" au lieu d'allez constaté si la la base est lock.

Ca sera push dans la 0.8.11-beta3 ou peut etre la release 0.8.11.

**Comment by m4dm4rtig4n** [comment]
@bdbogjoe la 0.8.11 est en ligne.
