### ISSUE TITLE
InfluxDB Issue even after cleaning and reinstall

### ISSUE THREAD

**Issue by beufanet** [m4dm4rtig4n/myelectricaldata#236]
Have an issue since 1 week. Multiple update on MyElectricalData to try to fix, 0.8.10 fixed the issue, but the issue then occurs again on 0.8.11-beta1

Remove the cache, the config folder and pushed it back, still happen.

```
2022-12-19 21:53:59.960 -     INFO :   => 14.613825332281365
2022-12-19 21:54:00.817 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 
2022-12-19 21:54:00.817 -     INFO :  [*******************] EXPORTATION DES DONNÉES "CONSUMPTION" DANS INFLUXDB
2022-12-19 21:54:00.817 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 
Traceback (most recent call last):
  File "/app/models/jobs.py", line 171, in job_import_data
    ExportInfluxDB(self.usage_point_id).daily(
  File "/app/models/export_influxdb.py", line 34, in daily
    app.INFLUXDB.write(
  File "/app/models/influxdb.py", line 167, in write
    self.write_api.write(bucket=self.bucket, org=self.org, record=record)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 374, in write
    results = list(map(write_payload, payloads.items()))
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 372, in write_payload
    return self._post_write(_async_req, bucket, org, final_string, payload[0])
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 483, in _post_write
    return self._write_service.post_write(org=org, bucket=bucket, body=body, precision=precision,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 60, in post_write
    (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 90, in post_write_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.6.0', 'X-Platform-Error-Code': 'unprocessable entity', 'Date': 'Mon, 19 Dec 2022 20:54:00 GMT', 'Content-Length': '221'})
HTTP response body: {"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \"Wh\" on measurement \"consumption\" is type float, already exists as type integer dropped=1"}
2022-12-19 21:54:00.876 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-19 21:54:00.876 -    ERROR : 
2022-12-19 21:54:00.877 -    ERROR :  Erreur lors de l'exportation des données dans InfluxDB
2022-12-19 21:54:00.877 -    ERROR :  (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.6.0', 'X-Platform-Error-Code': 'unprocessable entity', 'Date': 'Mon, 19 Dec 2022 20:54:00 GMT', 'Content-Length': '221'})
HTTP response body: {"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \"Wh\" on measurement \"consumption\" is type float, already exists as type integer dropped=1"}
2022-12-19 21:54:00.877 -    ERROR : 
2022-12-19 21:54:00.877 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-19 21:54:00.877 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 
2022-12-19 21:54:00.877 -     INFO : ▌│█║▌║▌║       ___                                 _     _____  _         _       _      _  _  _       ║▌║▌║█│▌
2022-12-19 21:54:00.878 -     INFO : ▌│█║▌║▌║      |_ _| _ __ ___   _ __    ___   _ __ | |_  |  ___|(_) _ __  (_) ___ | |__  | || || |      ║▌║▌║█│▌
2022-12-19 21:54:00.878 -     INFO : ▌│█║▌║▌║       | | | '_ ` _ \ | '_ \  / _ \ | '__|| __| | |_   | || '_ \ | |/ __|| '_ \ | || || |      ║▌║▌║█│▌
2022-12-19 21:54:00.878 -     INFO : ▌│█║▌║▌║       | | | | | | | || |_) || (_) || |   | |_  |  _|  | || | | || |\__ \| | | ||_||_||_|      ║▌║▌║█│▌
2022-12-19 21:54:00.878 -     INFO : ▌│█║▌║▌║      |___||_| |_| |_|| .__/  \___/ |_|    \__| |_|    |_||_| |_||_||___/|_| |_|(_)(_)(_)      ║▌║▌║█│▌
2022-12-19 21:54:00.878 -     INFO : ▌│█║▌║▌║                      |_|                                                                      ║▌║▌║█│▌
2022-12-19 21:54:00.878 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 
```

**Comment by m4dm4rtig4n** [comment]
@beufanet problem are fix but if you want remove influxdb error you must delete influxdb bucket and recreate it.
"wipe_influxdb" fonctionnality don't remove warning.

**Comment by beufanet** [comment]
does it mean I need to drop the bucket and the data into 😢 ?

**Comment by m4dm4rtig4n** [comment]
I don't have a solution for now on this other than wipe the bucket for now sorry :/

**Comment by vingerha** [comment]
seems the same one that I have (see other issue). When the values hit '0' the calculation seems to crash.
For my issue this is related to loading data beyond the date that there is history, so it populates the table with zero's and the export crashes as soon as it hits one of those records.

**Comment by vingerha** [comment]
@beufanet I am on 8.13-beta1 now, this issue no longer occurs (with me), I did drop the influx bucket once.
If confirmed, please close ticket
