### ISSUE TITLE
[BUG] - migration failed

### ISSUE THREAD

**Issue by roumano** [m4dm4rtig4n/myelectricaldata#239]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Souci lors de la migration 

```
mv cache.db enedisgateway.db

docker run -it --restart=unless-stopped -v $(pwd):/data -p 5000:5000 -e TZ="Europe/Paris" m4dm4rtig4n/myelectricaldata:0.8.10
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 0c07baa8d7b2, base
INFO  [alembic.runtime.migration] Running upgrade 0c07baa8d7b2 -> 09d887b265a5, add enable, progress & progress_status to usage_points
INFO  [alembic.runtime.migration] Running upgrade 09d887b265a5 -> 955ac9d18022, add consentement expiration date
INFO  [alembic.runtime.migration] Running upgrade 955ac9d18022 -> 4bb5f8f3d841, add all status data
INFO  [alembic.runtime.migration] Running upgrade 4bb5f8f3d841 -> 0b5c52e4efba, add activation_date
2022-12-20 17:13:24.228 -  WARNING : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ▲ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-20 17:13:24.229 -  WARNING :  MIGRATION DE L'ANCIENNE BASE DE DONNÉES VERS LA NOUVELLE STRUCTURE.
2022-12-20 17:13:24.229 -  WARNING : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ▲ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-20 17:13:24.231 -  WARNING :  Migration des "consumption_daily"
Traceback (most recent call last):
  File "/app/main.py", line 9, in <module>
    from models.ajax import Ajax
  File "/app/models/ajax.py", line 3, in <module>
    from models.jobs import Job
  File "/app/models/jobs.py", line 6, in <module>
    from models.database import Database
  File "/app/models/database.py", line 1141, in <module>
    Database().init_database()
  File "/app/models/database.py", line 41, in __init__
    self.migratev7tov8()
  File "/app/models/database.py", line 60, in migratev7tov8
    date = datetime.strptime(daily[1], "%Y-%m-%d")
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '19346888530116' does not match format '%Y-%m-%d'
```
**Configuration**
```
myelectricaldata:
  "XXXX":
    enable: 'true'
    token: YYYY
    name: "Maison"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.1740'
    consumption_max_date: "2021-06-01"
    consumption_detail_max_date: "2021-06-01"
    plan: BASE
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: 'false'
    refresh_contract: 'false'
```
**Type d'installation**
Docker
**Version : 0.8.10**

**Comment by m4dm4rtig4n** [comment]
Hello @roumano,

Je n'ai plus sous la main la structure de l'ancienne bdd, tu serais capable de me la donner ?

Ou même de me partager ton fichier enedisgateway.db stp ?
m4dm4rtig4n@gmail.com

**Comment by m4dm4rtig4n** [comment]
Ah tu as fait le `mv cache.db enedisgateway.db` j'avais pas vu...

La nouvelle structure du "cache.db", n'est plus compatible avec la nouvelle structure malheuresement...

Du coup le script de migration de restauration enedisgateway.db => cache.db est adapter uniquement au base généré par enedisgateway2mqtt.

Tu cherche à faire quoi exactement ?

**Comment by roumano** [comment]
J'avais cette erreur lors d'importation de nouvelle données  (j'avais tout avant 2022-12-08 , soit environ 2ans): 
```
2022-12-20 16:55:16.057 -     INFO :  Récupération des données : 2022-12-08 => 2022-12-10
2022-12-20 16:55:16.090 -     INFO :   => Chargement des données depuis MyElectricalData 2022-12-08 => 2022-12-10
2022-12-20 16:55:21.171 -    ERROR : (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) datatype mismatch
[SQL: INSERT INTO consumption_daily (id, usage_point_id, date, value, blacklist, fail_count) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('3aa746be921b35aa9ba7c406513e6740', '19346888530116', '2022-12-08 00:00:00.000000', '17290', 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: datatype mismatch
```

et donc tu m'avait conseiller de renommer la bdd pour corriger le souci.
depuis, j'ai supprimer la bdd et repartie de zero et là, ca fonctionne nickel
