### ISSUE TITLE
[BUG] - 8.12-beta1 - cherche des données hors des dates configurés

### ISSUE THREAD

**Issue by vingerha** [m4dm4rtig4n/myelectricaldata#245]
J'ai des détails depuis Mai 2021, 
date dans config.yaml:     consumption_detail_max_date: "2021-05-11" 
et... vois autre issue: pas de données de la veille
log ci-joint

[_myelectricaldata_logs_8_11.txt](https://github.com/m4dm4rtig4n/myelectricaldata/files/10292716/_myelectricaldata_logs_8_11.txt)

**Comment by buddy31130** [comment]
pareil, pas de données de la veille !

**Comment by vingerha** [comment]
Aujourd'hui, découverte que aussi les données journalières sont chechés hors des dates configuré
```
    consumption_max_date: "2020-07-07"
    consumption_detail_max_date: "2021-05-11"   
```
Le résultat est que le bdd est rempli avec des chiffres 0 qui ne sont pas proprement convertis vers influx.
Exportation vers influx maintenant impossible
```
2022-12-27 08:27:43.810 -     INFO :  EXPORTATION INFLUXDB
2022-12-27 08:27:43.810 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-27 08:27:43.810 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-27 08:27:43.811 -     INFO :  [25960347298299] EXPORTATION DES DONNÉES "CONSUMPTION" DANS INFLUXDB
2022-12-27 08:27:43.811 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-27 08:27:43.883 -     INFO :   - 2022-12
2022-12-27 08:27:44.158 -     INFO :   - 2022-11
2022-12-27 08:27:44.420 -     INFO :   - 2022-10
2022-12-27 08:27:44.654 -     INFO :   - 2022-09
2022-12-27 08:27:44.886 -     INFO :   - 2022-08
2022-12-27 08:27:45.126 -     INFO :   - 2022-07
2022-12-27 08:27:45.385 -     INFO :   - 2022-06
2022-12-27 08:27:45.621 -     INFO :   - 2022-05
2022-12-27 08:27:45.839 -     INFO :   - 2022-04
2022-12-27 08:27:46.070 -     INFO :   - 2022-03
2022-12-27 08:27:46.312 -     INFO :   - 2022-02
2022-12-27 08:27:46.536 -     INFO :   - 2022-01
2022-12-27 08:27:46.781 -     INFO :   - 2021-12
2022-12-27 08:27:47.037 -     INFO :   - 2021-11
2022-12-27 08:27:47.313 -     INFO :   - 2021-10
2022-12-27 08:27:47.562 -     INFO :   - 2021-09
2022-12-27 08:27:47.811 -     INFO :   - 2021-08
2022-12-27 08:27:48.076 -     INFO :   - 2021-07
2022-12-27 08:27:48.332 -     INFO :   - 2021-06
2022-12-27 08:27:48.575 -     INFO :   - 2021-05
2022-12-27 08:27:48.812 -     INFO :   - 2021-04
2022-12-27 08:27:49.030 -     INFO :   - 2021-03
2022-12-27 08:27:49.249 -     INFO :   - 2021-02
2022-12-27 08:27:49.467 -     INFO :   - 2021-01
2022-12-27 08:27:49.732 -     INFO :   - 2020-12
2022-12-27 08:27:50.020 -     INFO :   - 2020-11
2022-12-27 08:27:50.295 -     INFO :   - 2020-10
2022-12-27 08:27:50.530 -     INFO :   - 2020-09
2022-12-27 08:27:50.809 -     INFO :   - 2020-08
2022-12-27 08:27:51.073 -     INFO :   - 2020-07
Traceback (most recent call last):
  File "/app/models/jobs.py", line 197, in job_import_data
    ExportInfluxDB(self.usage_point_id).daily(
  File "/app/models/export_influxdb.py", line 34, in daily
    app.INFLUXDB.write(
  File "/app/models/influxdb.py", line 167, in write
    self.write_api.write(bucket=self.bucket, org=self.org, record=record)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 374, in write
    results = list(map(write_payload, payloads.items()))
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 372, in write_payload
    return self._post_write(_async_req, bucket, org, final_string, payload[0])
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 483, in _post_write
    return self._write_service.post_write(org=org, bucket=bucket, body=body, precision=precision,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 60, in post_write
    (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 90, in post_write_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.5.1', 'X-Platform-Error-Code': 'unprocessable entity', 'Date': 'Tue, 27 Dec 2022 07:27:51 GMT', 'Content-Length': '221'})
HTTP response body: {"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \"Wh\" on measurement \"consumption\" is type float, already exists as type integer dropped=1"}

2022-12-27 08:27:51.294 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-27 08:27:51.295 -    ERROR : 
2022-12-27 08:27:51.295 -    ERROR :  Erreur lors de l'exportation des données dans InfluxDB
2022-12-27 08:27:51.295 -    ERROR :  (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.5.1', 'X-Platform-Error-Code': 'unprocessable entity', 'Date': 'Tue, 27 Dec 2022 07:27:51 GMT', 'Content-Length': '221'})
HTTP response body: {"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \"Wh\" on measurement \"consumption\" is type float, already exists as type integer dropped=1"}

2022-12-27 08:27:51.295 -    ERROR : 
2022-12-27 08:27:51.295 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-27 08:27:51.296 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-27 08:27:51.296 -     INFO : ▌│█║▌║▌║       ___                                 _     _____  _         _       _      _  _  _       ║▌║▌║█│▌
2022-12-27 08:27:51.297 -     INFO : ▌│█║▌║▌║      |_ _| _ __ ___   _ __    ___   _ __ | |_  |  ___|(_) _ __  (_) ___ | |__  | || || |      ║▌║▌║█│▌
2022-12-27 08:27:51.297 -     INFO : ▌│█║▌║▌║       | | | '_ ` _ \ | '_ \  / _ \ | '__|| __| | |_   | || '_ \ | |/ __|| '_ \ | || || |      ║▌║▌║█│▌
2022-12-27 08:27:51.297 -     INFO : ▌│█║▌║▌║       | | | | | | | || |_) || (_) || |   | |_  |  _|  | || | | || |\__ \| | | ||_||_||_|      ║▌║▌║█│▌
2022-12-27 08:27:51.297 -     INFO : ▌│█║▌║▌║      |___||_| |_| |_|| .__/  \___/ |_|    \__| |_|    |_||_| |_||_||___/|_| |_|(_)(_)(_)      ║▌║▌║█│▌
2022-12-27 08:27:51.297 -     INFO : ▌│█║▌║▌║                      |_|                                                                      ║▌║▌║█│▌
2022-12-27 08:27:51.297 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Comment by vingerha** [comment]
J'ai trouvé la solution, dans export_influx.py
ligne 43
change ```
                    "Wh": float(watt),
```
en
```
                    "Wh": int(watt),
```
Il faut un 'wipe' après car l'ancien bdd ne connait que float

**Comment by vingerha** [comment]
Çe ne change pas la situation de MED cherchant des données hors mes dates configurés

**Comment by m4dm4rtig4n** [comment]
Sachant que je force en float() depuis plusieurs version, je comprend pas comment un int() arrive dans la base influxdb...
A moins que le client influxdb force de lui même le type lors de l'export :/

**Comment by vingerha** [comment]
Je ne sais pas non plus....pour moi float(0) n'est pas différent que int(0) mais influx proteste (clairenement)
Et je pense que t'as jamais vu ça parceque normalement il n'y pas de 0 dans le bdd.

**Comment by m4dm4rtig4n** [comment]
Bah des 0 en bdd c'est tout à fait possible quand tu as une maison secondaire par exemple et que tu coupe le compteur lorsque tu est absent.

**Comment by m4dm4rtig4n** [comment]
Je tente une autre approche, supprimer l'entrée dans l'influxdb avant de la réinséré...

**Comment by m4dm4rtig4n** [comment]
Bon ca augmente drastiquement le temps d'import.

**Comment by vingerha** [comment]
Les 0 chez moi viennent de la récuperation qui cherche hors des données dispo chez Enedis, c'est pur ça que j'avais les dates limite qui depuis 811-b6 ne founctionanne plus...donc j ai encore des 0 donc soucis vers influx.

**Comment by vingerha** [comment]
De mon avis, il faut séparer la collection des données de l'export

**Comment by m4dm4rtig4n** [comment]
Pour le souvis du "consumption_detail_max_date" non prit en compte c'est fix et sera en ligne avec 0.8.13-beta1

**Comment by m4dm4rtig4n** [comment]
Si quelqu'un peu tester sur le bug est encore d'actu sur la 0.8.13.-beta2 svp :)

**Comment by vingerha** [comment]
Oui...encore le cas dans section 'details'
![image](https://user-images.githubusercontent.com/44190435/212969045-53689530-84cd-4102-9b6a-e2dbe711ea39.png)

**Comment by vingerha** [comment]
Correction, détail ET daily ne respectent pas les dates configurés
Daily : 2020-01-20 > 2023-01-20
Détail: continue aussi hors la date (ci-dessus)

**Comment by m4dm4rtig4n** [comment]
Fix avec la 0.8.13-b3 normalement.

**Comment by vingerha** [comment]
confirmé et closed
