### ISSUE TITLE
[BUG] - Problème récupération contrat production only

### ISSUE THREAD

**Issue by ioull** [m4dm4rtig4n/myelectricaldata#253]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Je peux te redonner mon pdl si besoin, mais j'ai un PDL ou il n'y a aucune consommation, ce sont les vieux contrat de ventes.
Voici le message d'erreur dans les logs : 
2022-12-29 07:18:03.362 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-29 07:18:03.362 -     INFO :  [XXXXXXXXXXXXXXXXX] RÉCUPÉRATION DU CONTRAT :
2022-12-29 07:18:03.362 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-29 07:18:03.369 -     INFO :   => No cache
2022-12-29 07:18:03.641 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-29 07:18:03.641 -    ERROR :
2022-12-29 07:18:03.641 -    ERROR :  strptime() argument 1 must be str, not None
2022-12-29 07:18:03.641 -    ERROR :
2022-12-29 07:18:03.641 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-29 07:18:03.642 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-29 07:18:03.642 -    ERROR :
2022-12-29 07:18:03.642 -    ERROR :  {'error': True, 'description': 'Erreur lors de la récupération du contrat.'}
2022-12-29 07:18:03.642 -    ERROR :
2022-12-29 07:18:03.642 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-29 07:18:03.642 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-29 07:18:03.642 -    ERROR :
2022-12-29 07:18:03.642 -    ERROR :  Erreur lors de la récupération du contrat.
2022-12-29 07:18:03.642 -    ERROR :
2022-12-29 07:18:03.642 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════

Mais rien de grave puisque je récupère bien la production

**Configuration**
myelectricaldata:
  XXXXXXXXXXXXX:
    enable: 'true'
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
    name: "Consomation"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.1605'
    consumption_price_hc: '0.1605'
    consumption_price_hp: '0.1605'
    consumption_max_date: "2022-01-07"
    consumption_detail_max_date: "2022-01-07"
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: 'false'
    refresh_contract: 'false'
  XXXXXXXXXXXXXXXXXXXX:
    enable: 'true'
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    name: "Production"
    cache: 'true'
    consumption: 'false'
    consumption_detail: 'false'
    consumption_price_base: '0.175'
    consumption_price_hc: '0.175'
    consumption_price_hp: '0.175'
    consumption_max_date: "2021-06-01"
    consumption_detail_max_date: "2021-06-01"
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: 'true'
    production_detail: 'true'
    production_price: '0.60275'
    production_max_date: "2022-06-27"
    production_detail_max_date: "2022-06-27"
    refresh_addresse: 'false'
    refresh_contract: 'false'

**Type d'installation**
Docker

**Version : 0.8.11**

**Comment by ioull** [comment]
Et l'affichage est correct :
![image](https://user-images.githubusercontent.com/6410144/209931078-d82046a0-2725-4290-b4b8-3578103fc34f.png)

**Comment by m4dm4rtig4n** [comment]
Alors pour une raison inconnu, Enedis n'envoie pas l'information : "last_distribution_tariff_change_date" sur ton point de livraison.
Ce qui génére l'erreur...

Je vais push un fix pour eviter l'erreur.

**Comment by m4dm4rtig4n** [comment]
A tester, c'est fix dans la 0.8.12-beta2 normalement.

**Comment by ioull** [comment]
Je confirme ! c'est fixé ! 

Ceci dit j'ai l'impression que le paramètre consumption: 'false' n'est pas pris en compte puisque j'ai les erreurs suivantes : 
```
2023-01-02 09:57:07.716 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-02 09:57:07.716 -    ERROR :
2023-01-02 09:57:07.716 -    ERROR :  Echec de la récupération des données.
2023-01-02 09:57:07.716 -    ERROR :   => no measure found for this usage point
2023-01-02 09:57:07.717 -    ERROR :   => 2022-08-01 -> 2022-08-08
2023-01-02 09:57:07.717 -    ERROR :
2023-01-02 09:57:07.717 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2023-01-02 09:57:07.717 -     INFO :  Récupération des données : 2022-08-01 => 2022-08-08
2023-01-02 09:57:07.722 -     INFO :   - 11519m absente du relevé.
2023-01-02 09:57:07.722 -     INFO :   => Chargement des données depuis MyElectricalData 2022-08-01 => 2022-08-08

```

Et dans la génération pour MQTT, qu'il ne devrait pas generer d'après moi puisque consumption: 'false'

```
2023-01-02 09:57:16.769 -     INFO :  Génération des données de puissance max journalières.
Traceback (most recent call last):
  File "/app/models/jobs.py", line 160, in job_import_data
    ExportMqtt(self.usage_point_id).max_power()
  File "/app/models/export_mqtt.py", line 421, in max_power
    max_value = int(contract.subscribed_power.split(' ')[0]) * 1000
``` 

Mais bon je dois être un des seuls concernés et ce n'est pas bloquant ... donc t'embête pas trop pour mon cas ;-)

**Comment by ioull** [comment]
Ce qui est plus génant par contre c'est que l'interface Web sur le PDL de production ne marche plus : Internal Server Error avec l'erreur suivante:
```
2023-01-02 10:15:28.240 -    ERROR : Exception on /usage_point_id/XXXXXXXXXXXXX [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/main.py", line 150, in usage_point_id
    return UsagePointId(usage_point_id).display()
  File "/app/templates/usage_point_id.py", line 201, in display
    self.consumption_max_power()
  File "/app/templates/usage_point_id.py", line 407, in consumption_max_power
    max_power = self.contract.subscribed_power.split(' ')[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by m4dm4rtig4n** [comment]
> Ceci dit j'ai l'impression que le paramètre consumption: 'false' n'est pas pris en compte puisque j'ai les erreurs suivantes :

Tu as dû laisser activer le "consumption_detail" je pense qui est la récupération en mode horaire.


> Et dans la génération pour MQTT, qu'il ne devrait pas generer d'après moi puisque consumption: 'false'

Il exporte la consommation si "consumption" ou "consumption_detail" est à "true"

> Ce qui est plus génant par contre c'est que l'interface Web sur le PDL de production ne marche plus : Internal Server Error avec l'erreur suivante:
> 
> ```
> 2023-01-02 10:15:28.240 -    ERROR : Exception on /usage_point_id/XXXXXXXXXXXXX [GET]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/app/main.py", line 150, in usage_point_id
>     return UsagePointId(usage_point_id).display()
>   File "/app/templates/usage_point_id.py", line 201, in display
>     self.consumption_max_power()
>   File "/app/templates/usage_point_id.py", line 407, in consumption_max_power
>     max_power = self.contract.subscribed_power.split(' ')[0]
> AttributeError: 'NoneType' object has no attribute 'split'
> ```

Je vais fix le soucis dans la 0.8.12-beta3.

**Comment by m4dm4rtig4n** [comment]
En fait pour ton erreur sur la page web, c'est parce que tu affiche la "consumption_max_power" à "true" que ca génére le bug si tu veut ne plus avoir le soucis le temps que je sorte la beta3

**Comment by ioull** [comment]
L'ajout de concumption_max_power à false m'a permis de voir l'interface ! MERCI ! 

Par contre j'ai bien consumption et consumption_detail à false et j'ai toujours les erreurs. J'ai viré consumption_max_date et consumption_detail_max_date de mon compteur prod et je n'ai plus l'erreur "Génération des données de puissance max journalières" !

Il me reste un tas d'erreur de récupération dans la production détaillée : 
Nottement la derniere "Start date should be before end date" alors qu'il cherche du 2022-06-27 au  2022-06-27 ;-)

```
2023-01-02 15:18:03.926 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-02 15:18:03.926 -     INFO :  [23193487564154] RÉCUPÉRATION DE LA PRODUCTION DÉTAILLÉE :
2023-01-02 15:18:03.926 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-02 15:18:03.934 -     INFO :  Récupération des données : 2022-12-26 => 2023-01-02
2023-01-02 15:18:03.937 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:03.937 -     INFO :   => Chargement des données depuis MyElectricalData 2022-12-26 => 2023-01-02
2023-01-02 15:18:04.729 -     INFO :  Récupération des données : 2022-12-19 => 2022-12-26
2023-01-02 15:18:04.734 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:04.735 -     INFO :   => Chargement des données depuis MyElectricalData 2022-12-19 => 2022-12-26
2023-01-02 15:18:05.964 -     INFO :  Récupération des données : 2022-12-12 => 2022-12-19
2023-01-02 15:18:05.971 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:05.971 -     INFO :   => Chargement des données depuis MyElectricalData 2022-12-12 => 2022-12-19
2023-01-02 15:18:07.186 -     INFO :  Récupération des données : 2022-12-05 => 2022-12-12
2023-01-02 15:18:07.192 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:07.192 -     INFO :   => Chargement des données depuis MyElectricalData 2022-12-05 => 2022-12-12
2023-01-02 15:18:08.371 -     INFO :  Récupération des données : 2022-11-28 => 2022-12-05
2023-01-02 15:18:08.376 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:08.377 -     INFO :   => Chargement des données depuis MyElectricalData 2022-11-28 => 2022-12-05
2023-01-02 15:18:09.559 -     INFO :  Récupération des données : 2022-11-21 => 2022-11-28
2023-01-02 15:18:09.565 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:09.565 -     INFO :   => Chargement des données depuis MyElectricalData 2022-11-21 => 2022-11-28
2023-01-02 15:18:10.740 -     INFO :  Récupération des données : 2022-11-14 => 2022-11-21
2023-01-02 15:18:10.745 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:10.745 -     INFO :   => Chargement des données depuis MyElectricalData 2022-11-14 => 2022-11-21
2023-01-02 15:18:11.855 -     INFO :  Récupération des données : 2022-11-07 => 2022-11-14
2023-01-02 15:18:11.860 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:11.861 -     INFO :   => Chargement des données depuis MyElectricalData 2022-11-07 => 2022-11-14
2023-01-02 15:18:12.963 -     INFO :  Récupération des données : 2022-10-31 => 2022-11-07
2023-01-02 15:18:12.968 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:12.968 -     INFO :   => Chargement des données depuis MyElectricalData 2022-10-31 => 2022-11-07
2023-01-02 15:18:14.084 -     INFO :  Récupération des données : 2022-10-24 => 2022-10-31
2023-01-02 15:18:14.089 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:14.089 -     INFO :   => Chargement des données depuis MyElectricalData 2022-10-24 => 2022-10-31
2023-01-02 15:18:15.208 -     INFO :  Récupération des données : 2022-10-17 => 2022-10-24
2023-01-02 15:18:15.213 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:15.213 -     INFO :   => Chargement des données depuis MyElectricalData 2022-10-17 => 2022-10-24
2023-01-02 15:18:16.346 -     INFO :  Récupération des données : 2022-10-10 => 2022-10-17
2023-01-02 15:18:16.351 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:16.351 -     INFO :   => Chargement des données depuis MyElectricalData 2022-10-10 => 2022-10-17
2023-01-02 15:18:17.493 -     INFO :  Récupération des données : 2022-10-03 => 2022-10-10
2023-01-02 15:18:17.499 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:17.499 -     INFO :   => Chargement des données depuis MyElectricalData 2022-10-03 => 2022-10-10
2023-01-02 15:18:18.621 -     INFO :  Récupération des données : 2022-09-26 => 2022-10-03
2023-01-02 15:18:18.626 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:18.626 -     INFO :   => Chargement des données depuis MyElectricalData 2022-09-26 => 2022-10-03
2023-01-02 15:18:19.832 -     INFO :  Récupération des données : 2022-09-19 => 2022-09-26
2023-01-02 15:18:19.837 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:19.837 -     INFO :   => Chargement des données depuis MyElectricalData 2022-09-19 => 2022-09-26
2023-01-02 15:18:20.988 -     INFO :  Récupération des données : 2022-09-12 => 2022-09-19
2023-01-02 15:18:20.993 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:20.993 -     INFO :   => Chargement des données depuis MyElectricalData 2022-09-12 => 2022-09-19
2023-01-02 15:18:22.198 -     INFO :  Récupération des données : 2022-09-05 => 2022-09-12
2023-01-02 15:18:22.204 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:22.204 -     INFO :   => Chargement des données depuis MyElectricalData 2022-09-05 => 2022-09-12
2023-01-02 15:18:23.326 -     INFO :  Récupération des données : 2022-08-29 => 2022-09-05
2023-01-02 15:18:23.331 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:23.331 -     INFO :   => Chargement des données depuis MyElectricalData 2022-08-29 => 2022-09-05
2023-01-02 15:18:24.473 -     INFO :  Récupération des données : 2022-08-22 => 2022-08-29
2023-01-02 15:18:24.479 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:24.479 -     INFO :   => Chargement des données depuis MyElectricalData 2022-08-22 => 2022-08-29
2023-01-02 15:18:25.601 -     INFO :  Récupération des données : 2022-08-15 => 2022-08-22
2023-01-02 15:18:25.607 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:25.607 -     INFO :   => Chargement des données depuis MyElectricalData 2022-08-15 => 2022-08-22
2023-01-02 15:18:26.326 -     INFO :  Récupération des données : 2022-08-08 => 2022-08-15
2023-01-02 15:18:26.333 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:26.333 -     INFO :   => Chargement des données depuis MyElectricalData 2022-08-08 => 2022-08-15
2023-01-02 15:18:31.476 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-02 15:18:31.476 -    ERROR :
2023-01-02 15:18:31.476 -    ERROR :  Echec de la récupération des données.
2023-01-02 15:18:31.476 -    ERROR :   => no measure found for this usage point
2023-01-02 15:18:31.476 -    ERROR :   => 2022-08-01 -> 2022-08-08
2023-01-02 15:18:31.476 -    ERROR :
2023-01-02 15:18:31.476 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2023-01-02 15:18:31.476 -     INFO :  Récupération des données : 2022-08-01 => 2022-08-08
2023-01-02 15:18:31.481 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:31.481 -     INFO :   => Chargement des données depuis MyElectricalData 2022-08-01 => 2022-08-08
2023-01-02 15:18:32.575 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-02 15:18:32.576 -    ERROR :
2023-01-02 15:18:32.576 -    ERROR :  Echec de la récupération des données.
2023-01-02 15:18:32.576 -    ERROR :   => no measure found for this usage point
2023-01-02 15:18:32.576 -    ERROR :   => 2022-07-25 -> 2022-08-01
2023-01-02 15:18:32.576 -    ERROR :
2023-01-02 15:18:32.576 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2023-01-02 15:18:32.576 -     INFO :  Récupération des données : 2022-07-25 => 2022-08-01
2023-01-02 15:18:32.578 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:32.578 -     INFO :   => Chargement des données depuis MyElectricalData 2022-07-25 => 2022-08-01
2023-01-02 15:18:33.607 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-02 15:18:33.607 -    ERROR :
2023-01-02 15:18:33.607 -    ERROR :  Echec de la récupération des données.
2023-01-02 15:18:33.607 -    ERROR :   => no measure found for this usage point
2023-01-02 15:18:33.607 -    ERROR :   => 2022-07-18 -> 2022-07-25
2023-01-02 15:18:33.608 -    ERROR :
2023-01-02 15:18:33.608 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2023-01-02 15:18:33.608 -     INFO :  Récupération des données : 2022-07-18 => 2022-07-25
2023-01-02 15:18:33.610 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:33.610 -     INFO :   => Chargement des données depuis MyElectricalData 2022-07-18 => 2022-07-25
2023-01-02 15:18:34.715 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-02 15:18:34.716 -    ERROR :
2023-01-02 15:18:34.716 -    ERROR :  Echec de la récupération des données.
2023-01-02 15:18:34.716 -    ERROR :   => no measure found for this usage point
2023-01-02 15:18:34.716 -    ERROR :   => 2022-07-11 -> 2022-07-18
2023-01-02 15:18:34.716 -    ERROR :
2023-01-02 15:18:34.716 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2023-01-02 15:18:34.716 -     INFO :  Récupération des données : 2022-07-11 => 2022-07-18
2023-01-02 15:18:34.718 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:34.718 -     INFO :   => Chargement des données depuis MyElectricalData 2022-07-11 => 2022-07-18
2023-01-02 15:18:35.867 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-02 15:18:35.867 -    ERROR :
2023-01-02 15:18:35.867 -    ERROR :  Echec de la récupération des données.
2023-01-02 15:18:35.867 -    ERROR :   => no measure found for this usage point
2023-01-02 15:18:35.867 -    ERROR :   => 2022-07-04 -> 2022-07-11
2023-01-02 15:18:35.867 -    ERROR :
2023-01-02 15:18:35.867 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2023-01-02 15:18:35.867 -     INFO :  Récupération des données : 2022-07-04 => 2022-07-11
2023-01-02 15:18:35.869 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:35.869 -     INFO :   => Chargement des données depuis MyElectricalData 2022-07-04 => 2022-07-11
2023-01-02 15:18:36.898 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-02 15:18:36.898 -    ERROR :
2023-01-02 15:18:36.898 -    ERROR :  Echec de la récupération des données.
2023-01-02 15:18:36.898 -    ERROR :   => no measure found for this usage point
2023-01-02 15:18:36.898 -    ERROR :   => 2022-06-27 -> 2022-07-04
2023-01-02 15:18:36.898 -    ERROR :
2023-01-02 15:18:36.899 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2023-01-02 15:18:36.899 -     INFO :  Récupération des données : 2022-06-27 => 2022-07-04
2023-01-02 15:18:36.901 -     INFO :   - 11519m absente du relevé.
2023-01-02 15:18:36.901 -     INFO :   => Chargement des données depuis MyElectricalData 2022-06-27 => 2022-07-04
2023-01-02 15:18:37.891 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-02 15:18:37.891 -    ERROR :
2023-01-02 15:18:37.891 -    ERROR :  Echec de la récupération des données.
2023-01-02 15:18:37.892 -    ERROR :   => no measure found for this usage point
2023-01-02 15:18:37.892 -    ERROR :   => 2022-06-20 -> 2022-06-27
2023-01-02 15:18:37.892 -    ERROR :
2023-01-02 15:18:37.892 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2023-01-02 15:18:37.892 -     INFO :  Récupération des données : 2022-06-27 => 2022-06-27
2023-01-02 15:18:37.894 -     INFO :   - 1439m absente du relevé.
2023-01-02 15:18:37.894 -     INFO :   => Chargement des données depuis MyElectricalData 2022-06-27 => 2022-06-27
2023-01-02 15:18:38.344 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-02 15:18:38.345 -    ERROR :
2023-01-02 15:18:38.345 -    ERROR :  Echec de la récupération des données.
2023-01-02 15:18:38.345 -    ERROR :   => Start date should be before end date.
2023-01-02 15:18:38.345 -    ERROR :   => 2022-06-27 -> 2022-06-27
2023-01-02 15:18:38.345 -    ERROR :
2023-01-02 15:18:38.345 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2023-01-02 15:18:38.345 -  WARNING :  Arrêt de la récupération des données suite à une erreur.
2023-01-02 15:18:38.345 -  WARNING :  Prochain lancement à 2023-01-02 19:18:38.345373

```

**Comment by m4dm4rtig4n** [comment]
Pour retirer le "no measure found for this usage point", il te fait set les champs : 
- production_detail_max_date
- production_max_date
A la date du 2022-08-08.

Enedis n'a à priori aucune donnée avant cette date et l'API renvoie une date d'activation de contrat érroné à priori.

**Comment by m4dm4rtig4n** [comment]
Ton problème initial est fix dans la 0.8.12.

**Comment by ioull** [comment]
Parfait tout est réglé pour moi ! MERCI !
