### ISSUE TITLE
[BUG] - Problème export données production vers mqtt

### ISSUE THREAD

**Issue by ioull** [m4dm4rtig4n/myelectricaldata#258]
**Description du bug**
J'ai une exception lors de l'export de la production en mqtt
Traceback (most recent call last):
  File "/app/models/jobs.py", line 176, in job_import_data
    HomeAssistant(self.usage_point_id).export()
  File "/app/models/export_home_assistant.py", line 89, in export
    self.myelectricaldata_usage_point_id("production")
  File "/app/models/export_home_assistant.py", line 474, in myelectricaldata_usage_point_id
    "YesterdayConsumptionMaxPower": yesterday_consumption_max_power,
UnboundLocalError: local variable 'yesterday_consumption_max_power' referenced before assignment
2023-01-03 16:07:45.831 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-03 16:07:45.831 -    ERROR :
2023-01-03 16:07:45.831 -    ERROR :  Erreur lors de l'exportation des données dans Home Assistant
2023-01-03 16:07:45.831 -    ERROR :  local variable 'yesterday_consumption_max_power' referenced before assignment
2023-01-03 16:07:45.831 -    ERROR :
2023-01-03 16:07:45.832 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════

Je pense qu'il reste des erreurs de copié/collé dans le fichier export_home_assistant.py :
ligne 87 :        

>  if (hasattr(self.config, "production") and self.config.**consumption**

lignes 365/366: il reste du consumption

>         if hasattr(self.config, "consumption_max_power") and self.config.consumption_max_power:
>             yesterday_consumption_max_power = stats.max_power(0)["value"]
> 

qui fait planter la ligne 474 : 

>          "YesterdayConsumptionMaxPower": yesterday_consumption_max_power,

**Configuration**
  XXXXXXXXXXXX:
    enable: 'true'
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    name: "Production"
    cache: 'true'
    consumption: 'false'
    consumption_detail: 'false'
    consumption_price_base: '0.175'
    consumption_price_hc: '0.175'
    consumption_price_hp: '0.175'
    consumption_max_power: 'false'
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: 'true'
    production_detail: 'true'
    production_price: '0.60275'
    production_max_date: "2022-08-18"
    production_detail_max_date: "2022-08-18"
    production_max_power: 'false'
    refresh_addresse: 'false'
    refresh_contract: 'false'

**Type d'installation**
Docker

**Version : 0.8.12**

**Comment by m4dm4rtig4n** [comment]
C'est fix est arrivera avec la 0.8.13-beta1.
