### ISSUE TITLE
[HELP] - Erreur export MQTT lors de la première utilisation 

### ISSUE THREAD

**Issue by larod241** [m4dm4rtig4n/myelectricaldata#273]
Bonjour, 

Après paramètrage du module, il se plante à la fin avec dans les logs : 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:21:57.556 -     INFO :  EXPORTATION MQTT
2023-01-14 15:21:57.556 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:21:57.573 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:21:57.573 -     INFO :  [16232561439792] STATUT DU COMPTE.
2023-01-14 15:21:57.573 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:21:57.589 -     INFO :   => Finish
2023-01-14 15:21:57.591 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:21:57.591 -     INFO :  [16232561439792] EXPORTATION DE DONNÉES DANS MQTT.
2023-01-14 15:21:57.591 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:21:57.591 -     INFO :  Génération des messages du contrat
2023-01-14 15:21:57.594 -     INFO :   => Finish
2023-01-14 15:21:57.596 -     INFO :  [16232561439792] Génération des messages d'addresse
2023-01-14 15:21:57.598 -     INFO :   => Finish
2023-01-14 15:21:57.600 -     INFO :  Génération des données annuelles
2023-01-14 15:21:57.978 -     INFO :   => Finish
2023-01-14 15:21:57.980 -     INFO :  Génération des données linéaires journalières.
2023-01-14 15:21:58.033 -     INFO :   => Finish
2023-01-14 15:21:58.035 -     INFO :  Génération des données annuelles détaillé.
2023-01-14 15:22:02.145 -     INFO :   => Finish
2023-01-14 15:22:02.148 -     INFO :  Génération des données linéaires détaillées
2023-01-14 15:22:04.706 -     INFO :   => Finish
2023-01-14 15:22:04.708 -     INFO :  Génération des données de puissance max journalières.
2023-01-14 15:22:04.731 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:22:04.731 -     INFO :  EXPORT TERMINÉ
2023-01-14 15:22:04.731 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:22:04.731 - CRITICAL :  L'export Home Assistant est dépendant de MQTT, merci de configurer MQTT avant d'exporter vos données dans Home Assistant
2023-01-14 15:22:04.732 -    ERROR : Job "fetch_data_boot (trigger: date[2023-01-14 15:21:30 CET], next run at: 2023-01-14 15:21:30 CET)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/models/jobs.py", line 179, in job_import_data
    LOG.critical("L'export Home Assistant est dépendant de MQTT, "
  File "/app/models/log.py", line 97, in critical
    sys.exit()
SystemExit

HomeAssistant tourner sur une VM (HassIO).
Le liens avec MQTT se fait bien puisque dans le début des logs : 
2023-01-14 15:37:40.129 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:37:40.129 -     INFO :  Check config.yaml :
2023-01-14 15:37:40.129 -     INFO :   => Config valid
2023-01-14 15:37:40.130 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:37:40.130 -     INFO :  LOADING CONFIGURATION...
2023-01-14 15:37:40.130 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:37:40.130 -     INFO :  16232561439792
2023-01-14 15:37:40.133 -     INFO :    => Success
2023-01-14 15:37:40.133 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:37:40.133 -     INFO :  Connect to MQTT broker mqtt.larod.fr:1883
2023-01-14 15:37:40.167 -     INFO :   => Connection success
2023-01-14 15:37:40.167 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:37:40.167 -     INFO :  Connect to InfluxDB influxdb.larod.fr:8086
2023-01-14 15:37:40.187 -     INFO :   => Connection success
2023-01-14 15:37:40.188 -     INFO :   => Méthode d'importation : SYNCHRONOUS
2023-01-14 15:37:40.188 -     INFO :   => Aucune durée de rétention de données détectée.
2023-01-14 15:37:40.272 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-14 15:37:40.272 -     INFO :  DÉMARRAGE DU JOB D'IMPORTATION DANS 10S
2023-01-14 15:37:40.272 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ 

HomeAssitant est à jour, ainsi que le module MyElectricalData.

J'ai bien tenté de relancer le module, mais le problème reste le même.
J'ai aussi tenté de le désinstaller et de le réinstaller -> pareil.

**Comment by vingerha** [comment]
copie/colle ton config.yaml (sans token)

**Comment by larod241** [comment]
cycle: 14400
debug: true
wipe_cache: false
wipe_influxdb: false
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
  card_myenedis : true
influxdb:
  bucket: "MYELECTRICALDATA/autogen"
  enable: enable
  hostname: influxdb.larod.fr
  method: synchronous
  org: '-'
  port: 8086
  token: xxxxxx:xxxxxxx
mqtt:
  client_id: myelectricaldata
  enable: enable
  hostname: mqtt.larod.fr
  password: xxxxxxxxxx
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: larod241
myelectricaldata:
  xxxxxxxxxxxxxxxx:
    activation_date_daily: ''
    activation_date_detail: ''
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_price_base: 0
    consumption_price_hc: 0
    consumption_price_hp: 0
    enable: true
    name: Maison
    offpeak_hours_0: 02H00-7H00;14H00-17H00
    offpeak_hours_1: 02H00-7H00;14H00-17H00
    offpeak_hours_2: 02H00-7H00;14H00-17H00
    offpeak_hours_3: 02H00-7H00;14H00-17H00
    offpeak_hours_4: 02H00-7H00;14H00-17H00
    offpeak_hours_5: 02H00-7H00;14H00-17H00
    offpeak_hours_6: 02H00-7H00;14H00-17H00
    plan: HC/HP
    production: false
    production_detail: false
    production_detail_max_date: ''
    production_max_date: ''
    production_price: 0
    refresh_addresse: false
    refresh_contract: false
    token: xxxxxxxxxxxxxxxxxx

**Comment by vingerha** [comment]
@larod241 quand to colle ... le format en utilisant le <> du menu
Ça doit voir comme:
```
home_assistant:
  enable: true
  discovery: true
```

**Comment by vingerha** [comment]
Et t'as un screenshot de ton MQTT? ...les données sont visible dans MQTT?

**Comment by larod241** [comment]
J'ai utilisé le <> mais ça n'invente pas. 
Pour autant, l'indentation est bien bonne. 

Je vois bien les topics passer dans mqtt. 
![Capture d'écran 16 01 2023 à 18 04 17 PM](https://user-images.githubusercontent.com/20423481/212733241-f32928f3-b116-4c49-bb52-1e3466b3bc6a.png)

**Comment by m4dm4rtig4n** [comment]
> J'ai utilisé le <> mais ça n'invente pas. Pour autant, l'indentation est bien bonne.
> 
> Je vois bien les topics passer dans mqtt. ![Capture d'écran 16 01 2023 à 18 04 17 PM](https://user-images.githubusercontent.com/20423481/212733241-f32928f3-b116-4c49-bb52-1e3466b3bc6a.png)

C'est les données de l'exporter MQTT. 
Ce n'est pas le sensor à destination de HA.

Ta config est ilisible, mais de l'indentation entre quote stp.

**Comment by larod241** [comment]
C'est fait... Je ne connais pas trop l'éditeur de GitHub...

**Comment by m4dm4rtig4n** [comment]
Ton soucis est au niveau des lignes "enable".
Tu as mit : 
>  enable: enable
au lieu de : 
>   enable: true

**Comment by larod241** [comment]
J'ai tellement honte !!! 

Merci pour le coup de main.
