### ISSUE TITLE
[BUG] - crash au démarrage de l'addon si on change le chemin d'accès à config.yaml

### ISSUE THREAD

**Issue by chrsc59** [m4dm4rtig4n/myelectricaldata#282]
**Description du bug**
crash au démarrage de l'addon si on change le chemin d'accès à` config.yaml`

1. Déplacer le fichier `config.yaml` dans un répertoire à choisir, ou simplement renommer le répertoire `/config/enedisgateway2mqtt` en autre chose (`/config/myelectricaldata` par exemple)
2. Configurer l'addon dans l'UI (ou via l'edit yaml de l'UI) pour pointer sur le nouveau chemin
3. lancer l'addon

Log du lancement : 

```
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: MyElectricalData
 Use Enedis Gateway API to send data in your MQTT Broker (latest channel)
-----------------------------------------------------------
 Add-on version: 0.8.13-beta1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / qemux86-64)
 Home Assistant Core: 2023.1.6
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION=******
TZ=******
mqtt_autodiscover=******
verbose=******
/etc/cont-init.d/01-custom_script.sh: executing
[18:49:59] INFO: Execute /config/addons_autoscripts/enedisgateway2mqtt.sh if existing
[18:49:59] INFO: ... no script found
/etc/cont-init.d/91-mqtt_autodiscover.sh: executing
[18:49:59] INFO: mqtt_autodiscover is defined in options, attempting autodiscovery...
[18:49:59] INFO: ... MQTT service found, fetching server detail (you can enter those manually in your config file) ...
/etc/cont-init.d/91-mqtt_autodiscover.sh: exiting 2
/etc/cont-init.d/99-run.sh: executing
creating symlink
[18:49:59] INFO: Using database file found in /config/myelectricaldata
[18:49:59] INFO: Using config file found in /config/myelectricaldata/config.yaml
Config file is a valid yaml
 
 
[18:49:59] INFO: Starting the app
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2023-01-20 18:50:01.969 -     INFO :  Configure Databases
2023-01-20 18:50:02.000 -     INFO :   => day
2023-01-20 18:50:02.004 -     INFO :   => call_number
2023-01-20 18:50:02.006 -     INFO :   => max_call
2023-01-20 18:50:02.014 -     INFO :   => version
2023-01-20 18:50:02.016 -     INFO :   => lock
2023-01-20 18:50:02.018 -     INFO :   => lastUpdate
2023-01-20 18:50:02.019 -     INFO :   Success
2023-01-20 18:50:02.522 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-20 18:50:02.523 -     INFO :  RUN IN PRODUCTION MODE
2023-01-20 18:50:02.523 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "/app/main.py", line 31, in <module>
    CONFIG.load()
  File "/app/models/config.py", line 121, in load
    f = open(config_file, "a")
FileNotFoundError: [Errno 2] No such file or directory: '/data/config.yaml'
[18:50:02] FATAL: The app has crashed. Are you sure you entered the correct config options?
```

**Configuration**

```
myelectricaldata:
  xxxxxxxxxx:
    enable: true
    name: MaVille
    token: tttttttttttttttttttttttttttttttttttttttttttttttttttt
    activation_date_daily: ''
    activation_date_detail: ''
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_price_base: '0.1740'
    consumption_price_hc: 0
    consumption_price_hp: 0
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: false
    production_detail: false
    production_detail_max_date: ''
    production_max_date: ''
    production_price: 0
    refresh_addresse: false
    refresh_contract: false
```

**Type d'installation**
HAOS addon

**Version : 0.8.13-beta1**

n.b. Remettre le config.yaml dans le répertoire /config/enedisgateway2mqtt et reconfigurer l'addon contourne le problème

**Comment by vingerha** [comment]
L'add-on est une derivation de MED, il faut ouvrir un cas dans le github de Alexbelgium
