### ISSUE TITLE
[FEATURES] - Support de secrets.yaml pour l'authentification mqtt (et token InfluxDB?)

### ISSUE THREAD

**Issue by chrsc59** [m4dm4rtig4n/myelectricaldata#288]
Il n'est pas possible d'utiliser le fichier secrets.yaml pour le password mqtt (non testé pour le token InfluxDB).

Par exemple une configuration comme ceci : 

```
  username: mqtt-client
  password: "!secret mqtt_client_password"
```

Génère un échec de l'exportation vers mqtt: 
````
2023-01-24 19:28:04.163 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-24 19:28:04.163 -     INFO :  [19xxxxxxxxxx26] EXPORTATION DES DONNÉES DANS HOME ASSISTANT (VIA MQTT)
2023-01-24 19:28:04.163 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "/app/models/jobs.py", line 176, in job_import_data
    HomeAssistant(self.usage_point_id).export()
  File "/app/models/export_home_assistant.py", line 87, in export
    self.myelectricaldata_usage_point_id("consumption")
  File "/app/models/export_home_assistant.py", line 202, in myelectricaldata_usage_point_id
    app.MQTT.publish_multiple(config, topic)
  File "/app/models/mqtt.py", line 82, in publish_multiple
    publish.multiple(payload, hostname=self.hostname, port=self.port, client_id=self.client_id, auth=auth)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/publish.py", line 168, in multiple
    client.loop_forever()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2942, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3029, in _handle_connack
    self.on_connect(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/publish.py", line 53, in _on_connect
    raise mqtt.MQTTException(paho.connack_string(rc))
paho.mqtt.MQTTException: Connection Refused: not authorised.
2023-01-24 19:28:04.174 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-24 19:28:04.174 -    ERROR : 
2023-01-24 19:28:04.174 -    ERROR :  Erreur lors de l'exportation des données dans Home Assistant
2023-01-24 19:28:04.174 -    ERROR :  Connection Refused: not authorised.
2023-01-24 19:28:04.174 -    ERROR : 
2023-01-24 19:28:04.174 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by chrsc59** [comment]
@m4dm4rtig4n peut-on adapter l'app pour se caler aux modifications faites par alexbelgium dans l'addon ?
"(export of variables as ENV variables to the app)"

**Comment by alexbelgium** [comment]
> @m4dm4rtig4n peut-on adapter l'app pour se caler aux modifications faites par alexbelgium dans l'addon ? "(export of variables as ENV variables to the app)"

Le point étant que le fichier config.yaml est lu directement par l'app ; donc l'éventuelle implémentation du mode "secrets" de HA doit se faire au niveau de l'app et ne peut pas être au niveau de l'addon. Le code auquel fait référence chrsc59 est que j'ai mon propre système de config.yaml, qui exporte les valeurs en tant que variables ENV passées à l'app. Par contre, je ne pense pas que ce soit applicable dans ce cas de figure
