### ISSUE TITLE
[BUG] - absence de cache sur la passerelle

### ISSUE THREAD

**Issue by sh4rks** [m4dm4rtig4n/myelectricaldata#292]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Absence de cache sur la passerelle qui provoque des erreurs de récupérations de conso/ puissance. Erreur d’export mqtt par la suite.

**Configuration**

myelectricaldata:
  "PDL":
    enable: true
    name: "Maison"
    addresses: true
    cache: true
    refresh_addresse: false
    refresh_contract: false
    consumption: true
    consumption_detail: false
    consumption_price_base: 0.174
    consumption_price_hc: 0
    consumption_price_hp: 0
    consumption_max_date: "2022-12-01"
    consumption_detail_max_date: "2022-12-01"
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: true
    production_detail: false
    production_max_date: "2022-12-15"
    production_detail_max_date: "2022-12-15"
    production_price: 0

**Type d'installation**
HassIO

**Version : 0.8.13-8**

Trace:
2023-01-28 07:48:04.730 -     INFO :  [] RÉCUPÉRATION DU CONTRAT :
2023-01-28 07:48:04.731 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-28 07:48:05.029 -     INFO :   => No cache
Traceback (most recent call last):
  File "/app/models/jobs.py", line 74, in job_import_data
    self.get_contract()
  File "/app/models/jobs.py", line 260, in get_contract
    result = Contract(
  File "/app/models/query_contract.py", line 94, in get
    result = self.run()
  File "/app/models/query_contract.py", line 86, in run
    "description": json.loads(query_response.text)["detail"]
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-01-28 07:48:07.238 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-28 07:48:07.239 -    ERROR : 
2023-01-28 07:48:07.240 -    ERROR :  Erreur lors de la récupération des informations du contract
2023-01-28 07:48:07.240 -    ERROR :  Expecting value: line 1 column 1 (char 0)
2023-01-28 07:48:07.241 -    ERROR : 
2023-01-28 07:48:07.241 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2023-01-28 07:48:07.242 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-28 07:48:07.243 -     INFO :  [] RÉCUPÉRATION DES COORDONNÉES :
2023-01-28 07:48:07.243 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-28 07:48:07.263 -     INFO :   => No cache

**Comment by vingerha** [comment]
Soucis de la part d'Enedis, chez moi plus visible...stp verifier et fermer ce cas

**Comment by sh4rks** [comment]
@vingerha :
Effectivement, le soucis semble avoir disparu. 
je clos.
