### ISSUE TITLE
[BUG] - erreur conversion

### ISSUE THREAD

**Issue by vingerha** [m4dm4rtig4n/myelectricaldata#294]
8.14-beta1

erreur, pense liée a 'février' 

```
2023-02-01 14:49:43.268 -     INFO :  [25960347298299] EXPORTATION DE DONNÉES DANS MQTT.
2023-02-01 14:49:43.268 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-02-01 14:49:43.268 -     INFO :  Génération des messages du contrat
2023-02-01 14:49:43.281 -     INFO :   => Finish
2023-02-01 14:49:43.305 -     INFO :  [xxxxxxx] Génération des messages d'addresse
2023-02-01 14:49:43.316 -     INFO :   => Finish
2023-02-01 14:49:43.340 -     INFO :  Génération des données annuelles
Traceback (most recent call last):
  File "/app/models/jobs.py", line 121, in job_import_data
    ExportMqtt(self.usage_point_id, "consumption").daily_annual(
  File "/app/models/export_mqtt.py", line 107, in daily_annual
    get_daily_year = self.stat.get_year(year=year)
  File "/app/models/stat.py", line 442, in get_year
    end = datetime.combine(self.now_date.replace(year=year).replace(day=last_day_of_month).replace(month=12),
ValueError: day is out of range for month
2023-02-01 14:49:43.558 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-02-01 14:49:43.559 -    ERROR : 
2023-02-01 14:49:43.559 -    ERROR :  Erreur lors de l'exportation des données dans MQTT
2023-02-01 14:49:43.559 -    ERROR :  day is out of range for month

**Comment by vingerha** [comment]
@m4dm4rtig4n 
erreurs sont dans:
- get_week
- get_month
- get_year
J'ai les solutions...je les ajoute a mon PR ou je copie ci-dessous et tu le fait toi même?

**Comment by m4dm4rtig4n** [comment]
Fix dans les 0.8.14-beta3.
