### ISSUE TITLE
[BUG] - Retour erreur export vers Inlfux

### ISSUE THREAD

**Issue by vingerha** [m4dm4rtig4n/myelectricaldata#298]
v08.14-beta3 
Le soucis est comme avant ... la bdd cache est rempli avec des dates ou je n'ai pas des données (entre 2020-02-15 et 2020-07-07), alors value = 0
Ensuite, Influx tables sont crée avec la première valeur (de 2023-02) qui est int. Plus tard, quand les 0 arrivent dans 2020-07...l'erreur.

Ref: https://github.com/m4dm4rtig4n/myelectricaldata/issues/221
ref: https://github.com/m4dm4rtig4n/myelectricaldata/issues/245

J'avais des propos dans la deuxième qui marchent mais plus maintenant car aussi des 0 dès le début...curieux

```
2023-02-13 16:09:29.552 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-02-13 16:09:29.552 -     INFO :  [xxxxxxxxxx] EXPORTATION DES DONNÉES "CONSUMPTION" DANS INFLUXDB
2023-02-13 16:09:29.552 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-02-13 16:09:29.608 -     INFO :   - 2023-02
2023-02-13 16:09:29.707 -     INFO :   - 2023-01
2023-02-13 16:09:29.912 -     INFO :   - 2022-12
2023-02-13 16:09:30.124 -     INFO :   - 2022-11
2023-02-13 16:09:30.327 -     INFO :   - 2022-10
2023-02-13 16:09:30.544 -     INFO :   - 2022-09
2023-02-13 16:09:30.768 -     INFO :   - 2022-08
2023-02-13 16:09:30.991 -     INFO :   - 2022-07
2023-02-13 16:09:31.208 -     INFO :   - 2022-06
2023-02-13 16:09:31.406 -     INFO :   - 2022-05
2023-02-13 16:09:31.609 -     INFO :   - 2022-04
2023-02-13 16:09:31.830 -     INFO :   - 2022-03
2023-02-13 16:09:32.042 -     INFO :   - 2022-02
2023-02-13 16:09:32.234 -     INFO :   - 2022-01
2023-02-13 16:09:32.445 -     INFO :   - 2021-12
2023-02-13 16:09:32.668 -     INFO :   - 2021-11
2023-02-13 16:09:32.867 -     INFO :   - 2021-10
2023-02-13 16:09:33.086 -     INFO :   - 2021-09
2023-02-13 16:09:33.288 -     INFO :   - 2021-08
2023-02-13 16:09:33.497 -     INFO :   - 2021-07
2023-02-13 16:09:33.706 -     INFO :   - 2021-06
2023-02-13 16:09:33.919 -     INFO :   - 2021-05
2023-02-13 16:09:34.140 -     INFO :   - 2021-04
2023-02-13 16:09:34.342 -     INFO :   - 2021-03
2023-02-13 16:09:34.553 -     INFO :   - 2021-02
2023-02-13 16:09:34.757 -     INFO :   - 2021-01
2023-02-13 16:09:34.967 -     INFO :   - 2020-12
2023-02-13 16:09:35.190 -     INFO :   - 2020-11
2023-02-13 16:09:35.405 -     INFO :   - 2020-10
2023-02-13 16:09:35.640 -     INFO :   - 2020-09
2023-02-13 16:09:35.840 -     INFO :   - 2020-08
2023-02-13 16:09:36.077 -     INFO :   - 2020-07
Traceback (most recent call last):
  File "/app/models/jobs.py", line 219, in job_import_data
    ExportInfluxDB(self.usage_point_id).daily(
  File "/app/models/export_influxdb.py", line 35, in daily
    app.INFLUXDB.write(
  File "/app/models/influxdb.py", line 176, in write
    self.write_api.write(bucket=self.bucket, org=self.org, record=record)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 375, in write
    results = list(map(write_payload, payloads.items()))
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 373, in write_payload
    return self._post_write(_async_req, bucket, org, final_string, payload[0])
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 484, in _post_write
    return self._write_service.post_write(org=org, bucket=bucket, body=body, precision=precision,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 60, in post_write
    (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 90, in post_write_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.5.1', 'X-Platform-Error-Code': 'unprocessable entity', 'Date': 'Mon, 13 Feb 2023 15:09:36 GMT', 'Content-Length': '221'})
HTTP response body: {"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \"Wh\" on measurement \"consumption\" is type float, already exists as type integer dropped=1"}

2023-02-13 16:09:36.273 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-02-13 16:09:36.273 -    ERROR : 
2023-02-13 16:09:36.274 -    ERROR :  Erreur lors de l'exportation des données dans InfluxDB
2023-02-13 16:09:36.274 -    ERROR :  (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.5.1', 'X-Platform-Error-Code': 'unprocessable entity', 'Date': 'Mon, 13 Feb 2023 15:09:36 GMT', 'Content-Length': '221'})
HTTP response body: {"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \"Wh\" on measurement \"consumption\" is type float, already exists as type integer dropped=1"}

2023-02-13 16:09:36.274 -    ERROR :

**Comment by vingerha** [comment]
@m4dm4rtig4n j'ai la solution dans mon PR
query_daily avait une erreur dans 'get' pour la calculation 'begin' (months au lieu de days)
Donc ça resoudre la recherche des données avant consumption_max_date
Et en plus... avec la correction, ma bdd n'a plus des anciennes records et l'export vers influx marche

**Comment by vingerha** [comment]
@m4dm4rtig4n t'as copié aussi ma solution si-dessus? Dans ce cas, je close l'issue

**Comment by m4dm4rtig4n** [comment]
Ouai j'ai reprit de ta PR le fix également.

**Comment by vingerha** [comment]
top
