### ISSUE TITLE
[BUG] - MQTT 8.1.14b3 ERROR :  day is out of range for month

### ISSUE THREAD

**Issue by dudu7731** [m4dm4rtig4n/myelectricaldata#300]
**Description du bug**
lors du démarrage j'ai l'erreur suivante : 
Traceback (most recent call last):
  File "/app/models/jobs.py", line 126, in job_import_data
    ExportMqtt(self.usage_point_id, "consumption").daily_annual(
  File "/app/models/export_mqtt.py", line 107, in daily_annual
    get_daily_year = self.stat.get_year(year=year)
  File "/app/models/stat.py", line 415, in get_year
    end = datetime.combine(self.now_date.replace(year=year).replace(day=last_day_of_month).replace(month=12),
ValueError: day is out of range for month
2023-02-20 21:23:39.048 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-02-20 21:23:39.048 -    ERROR :
2023-02-20 21:23:39.048 -    ERROR :  Erreur lors de l'exportation des données dans MQTT
2023-02-20 21:23:39.048 -    ERROR :  day is out of range for month
2023-02-20 21:23:39.048 -    ERROR :
2023-02-20 21:23:39.048 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════

**Configuration**
cycle: 14400
debug: false
tempo:
  enable: true
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  bucket: MyElectricalData_dev
  enable: true
  hostname: XXXXXXX
  method: synchronous
  org: production
  port: 8086
  token: XXXXXXXX
mqtt:
  client_id: myelectricaldata_dev
  enable: true
  hostname: XXXXXX
  password: XXXXXXX
  port: 1883
  prefix: myelectricaldata_dev
  qos: 0
  retain: true
  username: XXXXXXX
myelectricaldata:
  'XXXXXXXXXXXX':
    activation_date_daily: ''
    activation_date_detail: ''
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2022-01-01'
    consumption_max_date: '2022-01-01'
    consumption_max_power: 'true'
    consumption_price_base: '0.174'
    consumption_price_hc: '0.1615'
    consumption_price_hp: '0.2228'
    enable: 'true'
    name: Home Enedis
    offpeak_hours_0: 22h00-06h00
    offpeak_hours_1: 22h00-06h00
    offpeak_hours_2: 22h00-06h00
    offpeak_hours_3: 22h00-06h00
    offpeak_hours_4: 22h00-06h00
    offpeak_hours_5: 22h00-06h00
    offpeak_hours_6: 22h00-06h00
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    token: XXX

**Type d'installation**
HassIO

**Version :0.8.14b3**

**Comment by Daarrz** [comment]
Je rencontre exactement le même soucis : 

`2023-02-28 09:24:36.022 -     INFO :  [***************] Génération des messages d'addresse
2023-02-28 09:24:36.049 -     INFO :   => Finish
2023-02-28 09:24:36.095 -     INFO :  Génération des données annuelles
Traceback (most recent call last):
  File "/app/models/jobs.py", line 126, in job_import_data
    ExportMqtt(self.usage_point_id, "consumption").daily_annual(
  File "/app/models/export_mqtt.py", line 107, in daily_annual
    get_daily_year = self.stat.get_year(year=year)
  File "/app/models/stat.py", line 415, in get_year
    end = datetime.combine(self.now_date.replace(year=year).replace(day=last_day_of_month).replace(month=12),
ValueError: day is out of range for month
2023-02-28 09:24:36.355 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-02-28 09:24:36.356 -    ERROR : 
2023-02-28 09:24:36.356 -    ERROR :  Erreur lors de l'exportation des données dans MQTT
2023-02-28 09:24:36.357 -    ERROR :  day is out of range for month
2023-02-28 09:24:36.357 -    ERROR : 
2023-02-28 09:24:36.357 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════ `
