### ISSUE TITLE
[HELP] - crash application myelectricaldata

### ISSUE THREAD

**Issue by Spifthespa** [m4dm4rtig4n/myelectricaldata#313]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Config myelectricadata**

Home Assistant 2023.3.5
Supervisor 2023.03.1
Operating System 9.5

Got that erreur at startup:
Extract of log:
2023-03-17 16:56:55.235 -     INFO :  Connect to InfluxDB 192.168.1.60:8086
2023-03-17 16:56:55.271 -     INFO :   => Connection success
2023-03-17 16:56:55.271 -     INFO :   => Méthode d'importation : SYNCHRONOUS
Traceback (most recent call last):
  File "/app/main.py", line 79, in <module>
    INFLUXDB = InfluxDB(
  File "/app/models/influxdb.py", line 64, in __init__
    self.connect()
  File "/app/models/influxdb.py", line 119, in connect
    self.get_list_retention_policies()
  File "/app/models/influxdb.py", line 144, in get_list_retention_policies
    buckets = self.buckets_api.find_buckets().buckets
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/bucket_api.py", line 119, in find_buckets
    return self._buckets_service.get_buckets(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/buckets_service.py", line 548, in get_buckets
    (data) = self.get_buckets_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/buckets_service.py", line 575, in get_buckets_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 365, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 268, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.10', 'Date': 'Fri, 17 Mar 2023 15:56:55 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
[16:56:55] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by m4dm4rtig4n** [comment]
Sans config impossible de t'aider :/
